# Model Predictions: what the Silver data contains and whether it is feature-ready

This is a reader-first, source-only dossier over a frozen Silver analysis frame. It explains the actual rows and columns before technical diagnostics. It reads no Gold dataset or model-ready matrix, performs no target analysis, and promotes no feature automatically.

In [1]:
_PAYLOAD_B64 = "eNrtfQ1v5DaS6F8R/HB4u3hum6S+nc0D5pLcIrhskktyC7zLDhqURNna6ZZ6pe6ZcYL576+KHxKllrrbH233OM4GG7dEkcWqYrGqWFX8/SytynXN0/XZ1e/4d7NZiro5uzorq1KcncOj96Lm12LOPxbwuNwsFudnWbXkRQmNllUmFvNqs15t1tA4r0VzU4qmmTcLLjvkmShTYb5b8o/zBb+eZ/xW9/Xp/OxdWX1YiAyGyPhazNNqYZp3bxqx5OW6SFsIFvxW1ABAUywAPhh6UeQivU0X0MGCNziBa1EC5GuRwduSrzc1X8zfiduzq1/fwoNqLbDRsijnMFPsdJ4DGpyicX786Ye/f/vztz98/+Y750+bssireumQC//PzkqUWVFew3/rWVNt6lQ4KV8UCQxTVKXzpx9+nEXOpfPm7zNKz52fv/3u79/8NPs7IfTPF84vN9B1La6LZl3f4jDrGwFNvv/rd984fLO+qepifevAWM57vthIPGyWZePwMnO2oPzTm/Wap+8c18kLBdL/CnCM25WAL2ohO//2+7/PmPPLm5/++s0vzgfoXtROk94AKr+ANnX1Yb6G9gaUdFPXolzPVje3TQGzcuTLvK6W8vVPxEl4IxZFKS4AoSterwucNKIUEPnr72fXCDV+hGRZ1wCURPxStHyS82WxuMWv6+qfIkXSXOV80YhP57s/X9UiK1I5HPLIWA9vbZhwOPhMYVvUkgXMvAxiJcwdGqD5gtfIambsXQCl1QZWDU4FacKTBTxc1xshgfjXRqzn7XC6h3//f798M3/z009v/h98tMaR1vPe6HoIREXveVGuA28ATlJcw2MLnLpazW8Fr+8A0Lff/yL7HYNFjTkERa28XWhpSr5qbqo1IBFExuHAqJ7vgJU7gLKqFkV6e0RYQBpusNs+PO1DDc/tHGTshi/uQKGvf/jvf//umwkS5YuKjxHpUGhWalWcACy/ibqa8xK2lMXt3MiY0wBtVRdVLRfWiQIIO3cB0FzPl4KXpw7jGvaX7OmBvJNYX8LWAfvwUwj2O8C1LkR9YiDlAlUq1MzW8yI7NXzJbk8MKNBcOGILddBTRNcJAqbURoM4UPQb0O5ODEZlB5w4kBKRJwZT+v7OutmTS7bmhp8YdPWmPD15y5t5lRvT7NiA7df9LXPxPpDttwDeSgM026Tog/j9LOHr9GYO6/+d+Rjsn/WmkaDoZueoB5UN+hLg8T+rpLmUn12ielTOW83jYnULMz5bgQ4FIMk59D0m52DW/mtTwBSNS0B5NBp3XlfVGqF0ry4vF+J9wdc3vJxl4v0M+Bjs/hkh9FJ5TC6VaO0w1UgiAHLmRq7JdvOxdj0HhRr9PZiM6CWqxVqU2A7nLuqZfo5TymvoeL6pi70giowbMFO+XPHiGnn+y1rwTNR5UTfrWV6UfDFjhAUkpNGM0zDgSU4v5RS+nIL9cr7k6Q0onZfGPLxEpwEMSi40M5yhl6osctGsnxlWA8bFPxu5n6AjbsFvkeF4xldr6ab7tXNzGTccUIPDgMDSDXAEcnvPFYZ+tLmWcbKDv+HIjjXyuaNMVQc6BL4U8MAo6/AnCCCnyJDIOWil2LjMHDW0sxRrjhuhdEEB698USQGjOkWJb82g6D/6unLKau1A9/BGOGqxObxpqrTgGgrgH1wuvEQ32w3QCZ5VtenGSWHgAld2Y7xU6MlCnFoDFGUuaoc7ah1KLx2oOeoDWIOifi9a6GGhK3cbkATmt7jFr5YVgFesLyRa6/RGaFEwRPv8XxteI26V1xTeXFf1wN9kuY22PCXb/grbGNEGwJbS3Sq6feWyp9BNKVGTiotRFuwNentTbDeiKWnb8/kB9iQJ56sFL6XrTf2EHq7ONAaXRdOAeEX/8ZlprrFtvQLDsZbYsaRP66S+rqVfWsnJdLOu8lw7A9Wj6eFATinBBRRbVfCr0Z5F5bUGTilwuVAGvwVvEBc9EMzDTVngp7+DwFsWZbHcLOfIV/AlCvV6VTU4nzdNA8M6zbpCsB3gnQV6fz8U6xuAzhEoYWEZlNfOUq3Obikgcyto5lmxFGUjhbLaAtRjWKoi1TJ4WYEcw1W2EJIozQoGmifaC76GDuTbqhRyxurhWgqNHySaZkgw4cBaX2SO6UjjbJI4iASNHuPmHyO4IduQ2i05b4DrlnzVI3df2bAXiVld92UIC5yn5YZvPuIfTuu/lkIIxweWMEC1vLFBXGsJ3aA8tCT3FG9MoekYDOPUIq3qzLGwOU3WbUZ5a2g9z0ST1sVKKR246XV0vzr7WYtLB3/DkICEBiACYZ7cyvMKXFrwS+sfFz1WuTr7K4JSouivHSUHZyWur0Xxm5BsrlpaG92Fhbmrs6/UX2MDq11F7mHym9Y1D1/B3w7+7SyqVC3vwRcO/Asco2HC7qtatoONRJQZV2C0cvnq7HvQqQDg94564vAV0AuefLgRpd70zDDAeBeDnQLwKDdMRz+05gt8Bt3gcRTu+8iAyJTysLBaLODVP2FZSIYbbEptn2affox+cctpO8bG0B0efV2LegUq+Vr1uq7MQLeyV6SOVL8Vmms8NVFox5WWwxq6aLc74Amzo8+MNiNFrwU6KLcgTZBryoU6qjMCHEcz8/mvN18ADfFYzdKAeNPiAzRJeSh6Mbk3X539Xf1lD47D4TQUVIZgZiLIyIvqukgvhjvv1dmP5kRPfaqeW9JGqvMtBkHjBCwXzY1hQrNsLyb3ehiifY4zrXK1LB/E5cMzv6uzr7FPoyIij4NElF23upglC7UYUj1Ne/ERdHirVqV+22q7D5uAVpBatu0rzoevg6FmaBa9eX740h8onTj3KhVy83bkqTlApmzO/szhc4nsolSi1Qwsu3FuYDaoGd9eTCuVgASFKoDrvSilSq/YzixYM5ZhbP1ly5bdSsZjdDUfrf2OLF1tTxx17VpKdkvj7XEPJrNU8e9LEvy4T4g9J0NXZz8JsIxwLh27SxGjv3Pwu3ZFGCoAf6ebhVyH8k2hrLl9Rzz7R5MfHjpce5YK6EI2adbKiENjtUO4ZgWjS1flFwOickNW1ac8EbV7XA4M453fj59iTk4cmx823U+4ZTc3ScXrbP5uVajAhZ62KaWMXnlSvTw/e1eU+BB9V1JrwUerYj7ScsETuf31tLdGet22B9GqWdulGmX41Aw0eG5G+kp3Oz6EilCZD0wNPdLEy3Zmo6/NuD/Lt30jZhyGLpLE0mI1COPvDASjbw0AP7ZbbvtyfHwZ6LM9dN9ibccctjbDfQ/P940k/SPoS5SG0jzbrKTbUVg4b5v0X5rRd/XQUty4amaykWM1QoU/EyDqsItaLJTz56ZYaSiVGTTuROk0emz4EVYtyqDWL6Q0IGmooQHWNjCKZYsaGahmPupLXdzBUJBnrf03eN9uym/aTUIrWCX8R0rrolUU5O6nnVSzhXgP4gXWvtySLpwOSeqNgfdSfFwrU264I2hHMDqtoDWitMAF/L4QH1B8gUIgAQCd7iOqiK0+1wWWKf+b6g3J3Vy0tnaLnnnrzC5BdZBaRsrVCb/1Zq6cxxL0uZEwRva1vmX1uqOLdB1rDFuEQ1Dm66pVYZF8bTPducXLY8TtjzH++nbepNVKnYBOAz9H8pyN9PG+aGAzWEiLssdgqrcpSDQxB9PVr81HWdGsqqbQRrn4mC42Gcx9Ifg7tchNw5vbVQUaADp71wIEm1xUuEO06v+CX1/j2qqSDZj23SkEeinSG14WDZ5IfCdbORIF5w5sfGt+7si4RuXhVZ93G7Yxl7Wh+8mCvfOEZuak5Vrb23PNlC1P/X5mvLBzdT7QxZtKF5m18GrBG4mNnmNKupthhVmDKs7mJfp/pTxOixVuqiB4zBLtlGsYG+G5rhYAAahk1QdrSM0KkgH0THqLwZzEQEcfqvrdHHZO5ZVHloQRiusbaLRZiMlNW21Y2v931n00/nbnLrjbwbRAuas3EDQWNyVIDBlBaRQl6eKTCsfvd3W3SWiV5tD3olmT2X7dag/tkwOmANYN0K/qKStKVN4f8m4lKnfhAPLt18Od0TzfAf9P0kbsdr7WlGgde2oXlN4JtCg5MhYeVqjFtSMWunuF7jn7aTm/4b/xWgqXzkjSiq3CYTM8qzFLRJ7ZNNqPguHezlAK4fppNy1H7exLDuazcAxmpK5rvNvtjHE9nTsliJraHLFIhdqEomPH8lTKmHNyqV9Nqd9mY5PLXu+Q0GQM3B8XPBU3sNZFfZnU1TuwlIEYfFFdd/6Qxrnh74XiKegGtu+1OslZ3EoLIC8W0qG0RCBG54Yj/WQivWHEdwisWa2OjkWfAWkvpQ08UzzbTv+LDn0KqSDeev3bAi4RFgo3azAb1gpWeWKljU5L3JqOgCV/QTvSgNkirrEO0hSaFXrP5XkaBzatCxDXl1pyAtQrOeHhUNvaAmAYVbktwa6fAwTAvtZjIWq1lXYH37gqOqnbiunJIbelMpq1AHa+WcCqrTa4GU1qled9EbIdhd45d2VKgbWlt5vV3w5faxcyRGEJ+E1tfdeKHG7DdqdiZncHrO6NFt1nx8MsLS/YXJ0GtMewWzJ3D8JWxXqu8zB+Pfu+coyS4LQCbYYjaIUVV4ExFL5w2sOB9+3y/+brN9gGllSRnTtJd+CMGF9Xa5kbUQqpH3TqsjoTmvH3MHOutDkHd2wpLb79pe3DHKkPfEOJSDmq8HLNwL+dK1KRXK+aUh+BK1Dl0lwpRR0DbEACHbpfAYGXvL6d6wMmrUtoKTSlamTo+0I77Ft5Gq6ECkrmnlQBpKozc7XMlJupFQ+WaJab4mArbE04YL+tbdGYgV/rRtJ7ZV4izPNelw1uDOqcJllU6TuhjhSbzQq3UGkmNpvF2qx3I062DNx22gbmMeu2fTavFeJbYNudWsUFrEcg7nVogZ3CBsLXjwT1wOofcwUYmH/SklFuEJpVZurotv9BN4X+82PNQS7Kng5rBJ31xszi21I+dHQT5SjuQ2199Rgg20tvDHyTxtZCj6ZWhQll13xlE+AX/dzRX0hC6DYd9F13jw38pNzYntIuPbydDorfkcPo/my6h48yHWsnttKaDgiYOaGN8vOJ3pnasKdDebb39TH+0jZqVhf5estyNU8Hnln5GM/RqwST+9BMBc7qMdugg8eWV7YWglrpzVKAOq3Pc9a3tg7S7oTmZTdLCwJ7Q5FJs2Pd9mZoPbzn7GBC6PfXmi46TEp1YFSgNr/qn2/Meqa0Of0C+9c4B8xxWWV7XYzZY52dGYNuxDKTjhZFuPZAkOL0lCE7H2jpLXPr1NK3h0emmlAUpXX/2HtnYnH2nAebcBAudctLR/odbw85Udv/5eTx2OSn1lHXjjb66GqyxdTh1MQHYCZ9uLmdg3oO1qSKMx2E37wp05uqBiux3e+sIAE70OZnxayN2UEacb2EP7vwmDakZm9LK5Dmx7pCzbWRajxo5mCgKxVVfJRSg3fBoU5W8OuyanC9gQ4nj5i31NBhVM0x+u/H3RxjhK1AnGMPoqJyjjGKick5Wt8jEQrHG6t1xX+lzv3BgjQhOYcF1zw+YNvRNftg2x1D8/gQtuEzx+h8O6bmqKNY8TaPP8hUxM0xBmsjbo7X+REFZBdi8/hd71MOjjropF5xjFHt6JujdG8CcY7Q+ZQi9Phjffokc8R0sJtUoLqkHDwdYtSLMVGkzRmSZ2R7s4ZkcklZlTK15KEJX8arhzs58wM8aRapl2cJJTSnsYhEnKR5kLsZFYIloS8Iyf0sBdCDDP4hYRJHzHdJEOU+z1OvVzFIn6z05q68nV2AufbsD983HN8r3X/83RweJKA8ZtY5wHhLPPo2UVBTw7URUbvabZZ73g7zMWTYhfSsXZ3lQCpRz/TpCSpS8oGFCXW+rExfMxD17bI2Q+T8Pmgd2Y211wyQP1BCVk0279KhzGoY1QmQ+2YkmLEQbQILPTGN1W95hmKNj7w9l0ePakJoaveBZAcD2VgyzWyldwPT97wRMNkhYNKDwMQdhVrY3AkeHYJHfTICHn0m8Jg/BM/1Twm8YAgevTd47AjgDYnLouBA3ns7ucbHhNygaSeUgtbJoqT53J6znJ/rBpy5WRwGkZsQESaMJyQIQjcNMh5TH9563M2SzA/jRESxEBlPvZjnQZqRJAdjD5aTz3LKPMpoSlhCcUvwfEI9wdwo5Dz1U5eJLAoDJpI8ySL4XxbFkUtzGC7PvVySKHCFJ3D/YJRTNxZ+EFMvjTOXw9Mo4tCURswFmJKcMdfncRxELGN+GlIa0kB14ok8pRFMKuPChbHcNOac+3nIuBfkQQZ7F3QLuyaJRZzFsHeRMKPwnxB2U0QpTCdIozRmEbwKuEcoiQA3fsjwOxEz3yNBmsYhifCvTAjYoGHIKIzdII55lqvphDnPI+aFcZDmgLGARyl1ecBTmiYJTIpSl0W5l6Sxx8PAS3x4kggC26xPMvgl+YIn3GOABD9OXB+nzyKgVCiATlS4IW7CHqApC2NG8kCwMEhDP05BiHgeol5CkrnEIwI7juMwIjHxApK6ggJeRZqSDOiKkABILEkI8f08JqFLYMpEAIlS6ORTa1Pg3lRLp+I8uZXntMBWnh+en21vmKjOYKiywBp5okxvjSUiOa9VTmDFkAt6QWSa9Xq1qNaLIoGH7gWlF6jclEm6KAT2iA1VyzKRyY/4zL+g5MJTB+UrXKTswrsIZHBBmfFG9kQuXPlgJWpYyQvZKJQdrW5lOj8+8aEZkX7JQvYDo4cSgEbwpKo1oO4F02GOjRQOjXqMQ2LAX4aaTJkX150ClbghCRgNYNWEwo+SKAlTkmQM2MjNXC9yvZB4OYsJTaMk4QKIEYdhCvzuidgnOBXsViO47daof5ykeQZrFJYOJ5ymMZAYhvTiNIJ1AcOSnIehm3EWA8tSD5ZpEsO6l8UZq99EqcPs2o7DBNY2rLdYUOAUmhDfzcMgjgSHGYjM81NY4anr09SPGY2zLHVTN/JCP0i83M9l8afCuIJEACyaRgyXXhazkMK/xEu8JAcoksSHF1keJIjmYokqYlZci0aqsBKeK0BB4AJykiwNWOYCHiOPZnlC4ZEfizwkMYoYP2PCywGvUeylIcuE73tRIjLseFuB0k8stUmAPY6UTPIszLLQDUQWB3EOsivIAhB4HBZvlhLpvG/W6GnWMcCWuP+FRlfUu6LB/5wdV+1qit/gIQWJA3M5pCTBlMJ/aUP05Tg8lwNovuxguUxhWczTpFrP5zLrESNcutoZ86HKNh8fYb4CWswXGF53nSytsgtaXkhLyOQMa0IFMRM5j5PcB7sjT1mYZGEkYBOBbSbiQbqXUC698rxXQj2AUPM5mMZc1hqd55hwoOLibg8joAsqR+onYUDzgIoszcOQwYLzMuKHsD8eRsCnWmmB77ovm4ArTPJm/aonO6gHuwxPQ5KAUAwYE6ASUR8UM9B/YFPz/Xg/9dgVJU+2/Ch5idTDfEGkHfMPXHNJ6qJ2ABoi80GXjaOcZDQCoscpj72YHrK7saeiWsDCFyQ0P14nFSyxw+hEIhJ4HAwzF/X/SISul7sCrKtAcOKnyUGy0X8iOkVRQF4cnR62t3mgGkegj9A8zVMO5mosPDCn0YymLErcg+jHXtfZ49DvjlubG4YijmKQhwlnJPZZnCcErBvfTTMvy/mJLT7yEol3953NDdw0cfMoBA0kzoIkCglLaQDmMQ+CbJ8+EsMygM3tDkS7pyf6iBrJGET3J9xqsWkkrUwZv/nUGEfXNcE4CL0ooJR4eR7nqceY64WeF2QsSYlI99PWvyJPSFvG/FOiLXy+rMr1DXxqaGnK7j05Ud8OXC89b7auwFnVKrTvRGsumvwHy1/mE56EaZLnrp/yNBXcA0OIsjzLhZ+SAAQQ/KKeT/KcU57nEaO+IKGfxKmb+TJ0WqirK+a6DAjmTORVLXAaKuQRj4WsVPh5eiPSdyY20jrU7B0tkLF39kGq/Fsl3+qUk62H4vq2LWFqmONESLNdunNIrK2gnt97J7Dybxm0u11TYE+A83hY/Z4A9e1w9LdWEjOeAv3lS5/If9pcfNvb/pcvgY1AFrqBF0m/NC4b6rsgEUMaemCCM+ZRD1WCduyBQ/7ennz0eZvDpYchCXPuWvA+g+KvGh8t03eOfU5YmEc+C5Oc+bmXiTT0QWWkEfXjJMw80B8Tj0RpHIiIguEW5CTC0yVoJEIZuNFWFpBZQ8ifmcCKAVyn+T8/YvoAnkwp3AkAt0vkTvj+G+wtLz6e6DQ0kHJrkE9G2A+PH90QNF2O7Af/l6Y+zdKMxcB2ru97QUiyhIH2K5I4Zy4Vmev5HM9oXZJ59Misva7WoEf2ZMun816lob5AwvQCLGTS39rUu5G+Bu96HUJPFpr8hKVRHLLcZWDZMc5iEmXcp65LXZbGYEFlKffimLt4GJfneZIBDqMUvvITMNYR6s0SE+f6cUuqUAieZF7z9FbVi0CW6OqCSnLjo9v+C0uv6irPyEPDJZZe2S43sXW3mSlF/oHDtwak9uoszL0sdEWRVbNZ9IPNrB1wfDs0Jdy3P9CFvtu2MJTOxzQrbGeP/bYq/6J7bHWPJ85W/Z0Duh62bju3kpHb7gmiyC6nsrNru6WNgEEBFqxnrm5eOwjgftsWXP14gAvMi7YS9qd7tRq2Hfy+q1JEm7Y4mT1oKTRTyWBjl7FNB4e/xUDItmK9iXaT+oZMuJWbIHxUyKBLs6h3THpHXx1eMaixR0FyQfrhOTsRa5dN013qamm6Oxnt8KnLhrBKhKgEcM1oW2wNSrrIc6y2+/6AIj97qhr1Kw5wVa9Y3L3ogM5E75W56WdgjU11ULGokuk7iK1brPKzs6hWF5J02CIf/bpjeaREVmEtgbmKr9y3xntt2372FZLa2ef0d/3+p2i2s/OJjzr5dCeCf2oproTHYeQY/aRPgx7T7OzMbmnjRwVNY4WVqU2s7Um+/A32F7BzdQ2JD2DazVe8lPmvvCzB+ELbWnm70M2lX+l63zKV0a7b//a8253smxX6mZIqAxJrsugFq24TaEuEflwb6fN2sPGM1vEyW4Cq2iDvrfzm6zez775585+ojqoo7bwt2nJTXN+gZGjLuPwqtwFT48ZwHwjf6wIdKwrTZ7ImedOoNJRfugIv6ILgRdkMawKBPYq5rhWsO1HPTFGbWixB9htz5T+FWFlx8abe5nKlE0NFmVe1Lr6sa3RI9w/H+0+xeh0q1EoAFXh1ytl/y+JUxXq0us+HarPAmyTWuhBsBpsA5girsp/Ki+ZYpX7s5Fn4L/o5rQTRvw7qdCiqytzZRqRtzfEMvT9FsmkfLAX8ThtzWe4aOGe+VbNlt1ib+qxTYtoHfcGkecd81xWZ1YVYuuG7fGZdQsGqOXTeVTo6twrVnuuiQqp+8aVVeEXJk4XKGcZM4JaI//VG0bm3DnRlEqeHuouz893C88C57cDRQHfZpZGMILPEW2OHlfwtRL5ZLNp6FAYtwDkNANpljLfVUgY3+EqpsBdHpjKw5I6Zqo5spMNd8Tc2ncfA3aOURji8TgOSSvkxb0DRqyuUyKrcYkeZ/+oK/11tld/R6erqAEASQpXjkVtHtgerYyMPNvPeEj5ItRz9ZJo0xBplSxi1OOhVROyXTZGTtosjSga0u2pLG+1BxzgYtgbwybairDaf2jKu76uUJ5sFVjCyq6/aUnXr5pwDLcKJz6ZRSz2pjskylo3RLBcLbUofJMv3fd3nFosK5tKgwU1aFklVkWQsIqtp2BYwH4jgLzSrX+ra4xoTty39S6Q5GE2gLhTWItB61r5FsBdoS4ocbjG2lU96tU5GPOZY+NXwzH4lvNfUMontdGq1qRdl5ycM2SQf6NLBNZeGj0Jsm28R6RcocObrm1o0WFlQ2prUvBrmIpmHyvYlF8x3qUfi2I8oI8QP0JO2ag8spUqofJkM/fzmKz8gIfNjGhOXURJ1dkDvjLL7WOYZ6W9JEIdxHMN/XNfzQ49tf037X7u+/TWLaBzTgHmEUhqMje33vqb2177rU5cFNI6YS0M3GPk6sL+OrG+JGzIWBDQkLqVhyGLX/poSCbl//6/jGXXv/3U4c8n9v/ZnoOnf72v6oHnTB82bPmje9EHzZg+aN3vQvJmZN8onq9zJtmyh9xIt5E6ShYzIFTIlSJR/TTWj2MxMq40iMLPShVm25+Sd2px8j3a0Yz4NPS/G1CnXdQOvmyFuNbiTcZvqB36b1Pw32Jfv/iFqH1i0fK2q3Vvfs8D63vPCwCdGNofW9+8wn1xoory3zraHZHFPjSyhZy0pn1IWwtbhe1EUMhrZvvWtqBIbTx6LLTzFLnNdErGQBGEQxGO92BGcdkcqIVN31AFCPAla15MVjqaw3qvc8xngva8rBF7g+TFjoRcA/intJjoIB+ozt2cjnUae78WuHzDYtqPJHrr4qUkFIKBB7AMjxAHoPKGtumh/XRuT1kJlO59NaaPPgQqeb008hDkHbuzSOPDjyNpNtqPxejyLumnLs25Agoi4oHmFhET+rk62Qvru0+uOYLJtssgMwM9gs+jTJQhD4sckBnXa811LCgCpRBD4NAt5GlKeuYLwyA2zhPp5KFI3iL00CJMsSEAVF1niCfgZZWHspy6IcDaNbxYA43sg6ElACLNWQJRnKUlzP3ApSX1OfBqD8CNh4nuMhDFPaOChZuIneURIDIpjkrp+nLM8iT2g3D2GDAPPzaNAkDxMI8aBPUUSpRnB5DqSBiIKSegmOfW4H9AsijmPojjxUpFHfp5l9D5Whi+8xMsShsnflARB4oWRF+WUunHGPU8wL2Q8p4zx1COuL2KaiiRNhSdiEUaRq1hPVwjbZjh2cgwH0tPaB30S+yAIGIhCj1mKggmztFEaBxargn6B2dxBGLuRHwaWINeR1BZitstBvaB9S8bdBBjty+B//v+A0IO5+iq8dVm9E/fYybo+Y8L88H/mlBOPBXGkOo917KyOY0Nd+T57nB4l+IUSL3TZ/8w5jAWrzFOjRHMriMSmZnsPzukTUVWGMSzLQMCQEASa5wdeTL3+5jKSC2EhNbD1NZBMoKsxDxDHQKAwa5vaKtMxSf0tX8t+PQZpYCrRjVh3/smZd4fJfSJgFwy8hMDGBesr4RERaRxxnuYhZi7dYytJIgp7BJhBfpYDliMO24VwUxFzlkQg8u/lkIoxwzQljCaJB5ZrxOKAsiiNEzeJg6xnyFHPtfsMYNP0wzD2XMZii+9oHmZZygX3U8/zI7DZItj389jnLMyTJLpHl2ksco/C5pimmQebMQ+wzgfuZdwPORX36NIPQMzHiEbsMg1QBwErRbgB1h1J2X26JBzjAaGDIPOSJOM+8zI/CqOUESpCco8uYSmCFSuICHKYbMIiDlJNsCAFIQpD5PfokqVuxklGXNBqvJzGoI2AUhUGkR8nGVhq9+gy90CLYhnqTEByzrkrQJ+KI+Ao3xVhfB9fZ5wEoLCIDPUxT4B+GMYpFqMR1MsCNwrv4wFNgVlAKrkJ6qJuLHgc5CH8XxIEkYhS0peNVpcu6IUsMC4ES4cFdTVAPQ7LkXhYKicgfh7lMCnhZ4Fw794jFgaKEp/73GUeLGoe+1QA6b0c+N3n0d17TPwsBIU6QtPIE64bRSiTAj9KMppHcapE8LCS5udgZ7i2f8farwSvYYspSmWx9blv4hO81e1uXyyL7A6tW/tRY3uipOhn4N4EHvdG3Zut6gVmE6Og4AWwzDJBmFK9Quk2UtNXZUJfjil7FxfD5Pb+IBfDdK87XQx3VxjSRbHEVkBH+zh6x+mz5cUQ5XVRCoFXsEkVvDBh09bxdBcfdkjsc+909OHhZMcKZN4RxDrn5krE3fHNh3TRQmEC148UQf1pC6xxysrgEryzFhhPXNf6BKcf4aXKo+rwKeMB3h3dtf1JPwygu3FIfvuAUOjJnvYGQo982TzK+FaYEZdxzqoq7jAcv/0Q0AMf443nD4Zh2NVE6Pb2+I9BgF4/d0C//q55hLEPQ317OZd1/azoR1R9078VrFg7WYVXp3VXg+F1ICA/a4x+m7wmbAfsE0DYAWmj+ZaTuQraRH87OcE5YOZfG3FPOh/Q5w6aU0lzfdGW/PCw6KKxL4bB5EodAch0Ix2AtIOlupDGLCtUJLnTKTIOz9eidkAELi9T0IsuP9wUa9GseCqGV/6eHxIZNQ7ZIYwqbzV/2PLc7mLvyrQ/aR424g4J9MmKMexvQPAG7yae1D86BpTNDgw5Hv/IWm57rxDrXd3Yy9fSXXbBfHfD2FRHd4zeKucS9b0gh/Zpaw4cFK1xh652h0gc3lF3tc1IV3cBSiZQgIT+ACtPI1TmV85BQPZkPN79isJlIWYmEQAzREzYdSNvyHaaTZ3Dym/aG+pVOqzT3JbqznFniZeCQ+ddELQZXu4QC77St4d/mMkTenWNvYRpjwSZnMaWGtkWaejuDv9Y7E9nGf2o7VxWsOjW6WBRdvIcf3aXGA71x7ndCme0XyovFlIYfoGXCywrwC5lKmIfL/Vtb/DWa/jcacRCSdDEfglcghuzih/dg+hRKDvZADZPtb4xTbrq1mB59l5058mddwvLOp+fLUSOQrB/yR0+bL+9Lt4LQK+8cls/0+a7DdkC73y7Ci98PBYkURjSmMFAwPE3hW4uu8Ctc+LWvN4QelgbEr0iP8s5747bf8kzn7wL8SVPuhc5/aInui/j5A8x+clsmpc8+6nbW596zlPbyR9JoD8PDk5GtD/P9J9VyD/TlE9N3D8zGk5G8D8PHo6yBdCATE0/9DDWgBCPRhiB4bXTn0puu/f06YXrRhi4SfBym8gL3VEBOCwr99Rk370L/UGk/3Mi4Vn3gGed+KntBCeBjJPZD54TG6diGEwKqBcsEp5rzqcmDZ4bDycjCJ4JEaciA3qL8Q+2Bp5j7ifD9084+ZPh9X0M+IfjgedFyMnxxSRhPkcvAQadjuJhJAL1abzj5CLES1tJHEcB/BGHtMPBIEf6kMmTC58FLvXDKPZCN4g89pi4eDKH0WeFlSc2mz4r3DydJvlZoeW4isbnhYon328/T/Q83T78WeFnSk94OVi5h/LWVRV6ACJc2b/vkoAy5mFIm8aDH1LikihgPo0iH1PADR76utIhSPCo70E3sU88N4R5BC8AC/cPVXuZ+Hho1MPLxMoDTsJeJkLu6AJ/oUh4uD/whSPmAY6il4mZ+3tK7oCP+6hmR0EIcVuUeIQQF0s5xDC2R2VlpYcoZIxGgR9FMaMsYmEcRVPIkHVsRpExUtTmyYNNAApQUf2YuczzgbiyeKVBjE2TgxiEhR71XJdgXcUg8h8TJVuBMC8EF/c6eT82d9AWIwxLOGGtBNdHWyZ6iPpOw9AHsyjGlR97bsxeHE4eosy/fOw8XLV/+Th6kKL/8tFzZ7X/D4CSxzAC/kBoepBJ8PLx9BAD4ZjYOaL+9/lpO8+MjFNVc54ZLaet3zwzck5WsXlmvJyURvPcuDh1VeZU8HOyOswzI+hJlJf7Rf08nUOP+rEXRtQjYRiT2LOdWPfydFoo8RnebvOoIT9P4dY7PkbUlUny3kELsnuUQ9ruY7ISkrxpd44XLXYkIIcXC9LFrqwPu9ey6Ggjb0sSdpP2UdtsWFLpdIBqizOdDEh2maeizAu8Gsr6qH1k9V2Kay7vireGN4/sZo81FylAu9fyZ28O9g1UByKWeoG7BQy5CCICazL0o9gPA98L+7DJI4Je+5GjgUMxP7jB6VC4ZS3hLbijIHQjQsMgYoHnkrgPt9wze+2398pDwd6+9ehQyEHWjkAeuwRv14L/yGLpQR9yKb37/LAtte8Dur4Z6FSWYXtzzEkBNFZt+3Ph0+ElJaeC2HGl63AA5e0hW3jdvkakRwxZWqD3wXZJgXtM4NQ2/V2+jvtvbywORjY46obAyl7kEgoqf/CEK2DfdthdDXMqdNm+KeFzYfbpWwc+Fzmob7U+IW6wnEufEx71BQwng8Xdbqn7izsqr0jdkncRxdsY/YhRlzLmRick8PZ5oI5u2TzJzNUgvckPB/hkXVf/gP3OZ2P7HQ1ZABueG3gRI5E0jZ7KwLudo9LxkCnhFUrbUwKrA7aSKPRZTCLXfcIZjfsE/ziM+kl6Q0pT7P0A/1RXjFiXIHadtoOu8nDgqN0F/sQSz4w4C/FeLJq95YbHQelVHNZUOiQ8sO1P1zWXQ7RFy9uXw/u0u4L8rS7jdc+68WiId6Ay5oEJHIy5HcGsDoMQbzMNXOq6LpKo1Nd76+23A6z1nkgX6vFm2V11vj3PcGyejAbyvnsXFqhL8YKuMQcrISGoiQEJvZiGse+qmWKF8mebqb6Y/aVPs3+N/GnPdltkPdYaDYLtWVLmezC/yKchpYRhXPfoIvUCykK8NJ74cSD3qIlFajsLjzvPHasUDy+2x8Oba13ixTGQLIy8CXriHZwx3gHmU7ed6Rg9n26mU6v0hU1zzyp9abN91mU67jV92Qv2Oeb8rEv3OSZ8Cov4HvPedrw91nJ2Y7I9ZUxu8bwoCGJGqM/oxHKOWegTvPcxQF9GOL2cx331x53xjuXsEX9szhFMIwgjN3TdiE3qU6DjxR7xwNhF1ExT+TnmPLWcX+yE9yznU533Z7477zoeetl79PPN/Fl36ueb9ins1/ee/We+aw9OG1/2dv2kk33WffpJZ3oKG/RdJnyYM09FGY3N9+N1UlXNenumvjciqvyABbHnEuJTPBacmGkYsJAFMF1oFpJITjTGXfyoDsvpOS4wiPY6WY54KscmSRkJw5Aw8687LpdcoLePEbceMBuJFT0pRfF9TFflPUgpz3GGg7HYd5FnQz/wQIWKRmfJLlif4GyamI/r6rkPNUe2GDJOO7KDWE81j2cm17GcGc9HuGO5Ke5BwjjYIuEd8gSmSHYsg/U+JAu8EaL5sD1a/06cUIbMDWFjiGIaMq3GjhP0WIbqya7J45otz7cyj2uQnMz6fHRF9VQX5uMrqL280+3p/uX7//7uu/970LI8uDhZqT8/qlK6Z16ruso2WsLphbFKR/iV0gfNU37+rPNssvmhc2XRmEswAF2bEcr8EGytwPXGOdiHSfshWGEsonHMVPALDRENx9TJj869I4V9p9j3cdXXR+Lfu28jzz6zO3DsnWc3ypBPOr0nZcljmRqnxJzPNccnZ9NjWVlHZ9gJTW6UY49laT25OjAx6VEWfq5J34GFKRvzv8LEQB+HrT9moRuFU+cIoA9Frk/jENZdxNgOHj+W4XlKQvm4tuYpiebnnemTC+jjGtsnJaYf3eA+afn85LM9PcE8RAEWOrG75CVA2BTNvNmsVlWtsh+nsz92fmpVOkmrYZ4KYP26SBZCg9ah4fxsxYvajm6pBW8wc/TszWLh5DWM7NTVh8b5IGrhCBwDsJU5eVU76xvhZGIt6mVRFs26SPlicesAiUWKTXSyC6a0mGcj4+PR5QYnqycisrPdOTdDzoCHv1pnpMYJZXHLW2tWf+s6c4qmS80BeKvSSaCbDP5cVB9mKa+zAsYv1jAnmV4LU7teinItp1SLtKqz7vhxdCYDlpCgTlUz2irmYxfN7ldQnCohuEuWvpW5TLX416aoJSGWq4XAZK3qg5nEXevt7OrsXB5NYyNgno45ySQMtc7RfwwQaoVRDQEwsUS3BYXMbYMfBVbeuesynP7OWoPlZinqIp2bxvazVPQKh+Chbsuf/yFT6M6d7/n3l5jLdu58W+bnDmapnTsmdU4ljcnSQaVjsm6dFB4WyEx6scoRRCbX3+gi08nBpgO5ulpAvqrKvLjeAG6dtfiIqZrdSOvqnSj7ozg8B0HgQI/LyxR4zimrGhiw+I0j6idgaEGwMeJGIFUls7aIbjbLJVf1iNr0uu8VMq3p4+eNwwGmG7GppUACgVUAQ8HSrcrF7ReOJI9qUwpYN04tltV7XPs1SLJ0wXG6RSkHdj4U65tqs3a4Xv6zZiXSIodeQWqskamcerMQe1L2tiZhl6TKc1ssNmOJlb++xa7KOSxsO9nx1z0FM/dWA9xfDm889/PtdlLng2Fpk4HbFFocRa+WLtHc8LeNGjuh89f7Twqr7vTQTl15/8VImusIMSj1RvOTXXq+a9HvnyHe0ooLeg5MikN2XY3yitK0t+GD5xipx0I/AMWNRv0047YRhYXnU0LdMCC+75LwIBC30ogvmAdjsZiEQeAFsee7n6YX+pYUsrbKt2Mv22IDgzcTSc1uyCItSzat+rOqVpuFFEx333GmOuqWtZRdIypbuxVgBZhiPV8I/k6XGVkKmE0qaWqKP7UqmxI+Pdn3V1GKWqphUhOYgZRagaBaLXgpvnCyCsYE2YYiT24UiA9H92vtEnsE1xQg7URzvmgEzOVdWX1YiOxalh8Rrfa7cw8d/6btGpm313MjlhwIrVB0UL/dF9O9roslKAyCg55nFOVDuh58Zgl0EChFowbCTHC1ocy7Lw1uVIMBEiR/aD5WDaqkEfV7rnTFj4VWf7e9PlqDrEUDLxVbg8aoGG2TgAqpuljwa2h62wLY7vXfC9jqgGO4s2k4kBo1/plMSHdaGGc4a63T4+YOjcuqnBkp4lyjiEI12hrRgRFRy+bvgW+x454eUAqRNXOzl6LMQo12nhcfzz7pJXJHzWz0E4s8NZghIPIRET1d5xcwZGpxDSpDfevc8AZmZk0csasn3oN/U/a0qRp0DdTDYe/h/4RtvaoL0Tz2MJ8mSbobMWOftAqy/tVfJRau5kaL2jPK6Ce2XBxD0u3hve/4tCuAgFv5+6JEGwrW6Bq3h2qfNNpu3/Z3thL1TL8/swS7LcBxe0tvQN60zDyQ6a3V273dX8a0bT1Zw7QVMEgyXF5nV+t6IyzJs75dYY9qr0QzUoDUSHHn0OLbyBhom3WN0ZTk9bpQqNMNW4Zc8jXMVpvpVvXSUwCnrVt6AsDYFUsPBgc4LfAOhMa0PRAeu/ro86NnUFb0+QHaLhh6WjDpSqDPD1RbA/REQBmrencqoHV1PUcg0l8/LkhqmmMQTVb0fH5kjdTqPAV87azSeTDW8kXFDxfqXevDUNdV0Xx+MrYu7CNvNMp82QWTLjc/WtPzBPA0Wa3z+WHr6nCeCiynoyKY2ponAMneqponIp4OqHl5IpDaFSlPBiRTT/JEAJosB3kS8H3q7hFpTzQPsbN755XG/dxa3cz/ZE3jDv2Pf7NjoAAH2qykp6Z1MWNn+9w7Ex/1nSIm2mEAVnNY0MH2Z13vW/u+PZx1QnuX4bY+60+m5ZTDet1qbgFvpVe3FvvIafz2GdX55I1JRz+a6/wuelM6376LR2/kw9iBXhTNVCDB5H1zbYqPFZswNFJbnfT8rBfgMBX40LOUtm0BJHcvSGGXj3Bf/AEe73zCd+LjauvodUfHIx/YDNn5BYeOwM43mNUygKh/2FNVa4HhN4BhU3HeAkK9nmWiLt5LhjNHM4PPLA9h+0qFQxgxXCXoMu3OHy2BijXCgYDLNgioJT92UgMkMOnkFusLgCwMPD9sG1hkkYj9tNUt751bYUhR28BRDeRhPKy0D+XwPGpq9ltD2NVv+xONbIDU4b+kQM82n4gcG2HFqzNGWDAjwYyFZ322jGmsfl/X1WZljY/8J0+AtK2JcXB9INnBQDaWNDAC6m5gyosKtsBkh4BJDwITpRG1sLkTPDoET16jswUefSbwmD8ED8/NTwe8YAgevTd47AjgDYkrM+UO4r23ndSEDQWEztyGtunJlB9BRKi3zo+8/tdGrB0lOBzVg5PDTipq2JLhyy+c5WaxLkA04vnbjWgcrWc4IEgv8wKPPsX7Qnw4VBbtgtKSyq4bcOZmcRhEbkJEmDCekCAI3TTIeEx9eOtxN0syP4wTEcVCZDz1Yp4HaUaSHKQoLFuf5ZR5lNGUsISGviCeT6gnmBuFnKd+6jKRRWHARJInWQT/y6I4cmkOw+W5l0tWCFzhiSwjIaOcurHAQHEvjTOXw9Mo4tAU40MApiRnzPU5BvqyjPlpSGlIA9WJJ/KURjCpjAsXxnLTmHPu5yHjXpAHWZLm0C1PchKLOIsJyUmYUfhPyGmICj9MJ0ijNGYRvAq4RyiJADd+yPA7ETNM+03TOCQR/pUJIXgGQ0Zh7AZxzLNcTSfMeR4xL4yDNAeMBTxKqcsDntI0SWBSlLosyr0kjT0eBl7iw5NEkIQSn2TwS/IfT7jHAAl+nLg+Tp9FWJZcAJ2ocMPczagHaMrCmJE8ECwM0tCPU4zi8RD1EpLMJR4R2HEchxGJiReQ1BUU8CrSlGRAV4QEQGJJQojv5zEJXQJTJgJIlEInn7b1CKU0oB0tlquq5gvc82Dxgb41UCX4Zl2lVV0LFY/SO1VtF8sPNXAwRvQVYB+s+XKlT/mXsIh5CcujKNPFJoN1IWRoGh7sL/j1DIOEdYDdnqiRSTD6+nvK5VPYzbL5NV8degY8+Zm11jpDhesuB+EYyl5s5kWZi1ra17oBhgyWsH5b7LRllM7PcDQTUqR+4ak59PURdnkMOuoeSVzqEPruKUjS4bNV7GMODIt7/8igMwlYNwPQ4ZVyvEDtfW4BQ+1nbRL04J9PtgWbg0p3IwOS2u4PM2O3PxzGDCAG6yLZqO0AWXecDb8WTVoXK8leYCQtbi8XGJC0dgyXz/61wd1ogQERS9iYiqYqv8BwCWW9YEzJplGhrbsg3wFOnx1XHEPIEr7g+/HRb2sfzpvIExk1Px/roo1SxjCD9a3FX8M3VhpG29aKdu/MP2O+vrUamk5zjAHUuroGeA7EBPbOjGFwvajgzbzl/RXscFVm9dGazv03IHuQ9TGxXfO7p1JGSvlwRYl+sorVX4hl04MyW3CORaXEmLVk5Ke0/ZSq+61gNUqTGNkix3ChlL8Hu9Os3SatlMMIZ9wnhAomqqtrNGVkvOMG5nOoxNnxYZ+FMLAHqN7cTHL9z+u6AlUE2NykGei4Yhmop3DgNDDN9d1ZfXz0PoSNjEOSCQ2Hzn70k36v7cZ0x1it6e/sJdXfTXT6h45Ln2PayRIM11VVSK0wskPaqi4iDePU4DMQ6eVahYA7wNMF7HJLIdaNzGPpunV0t470vjiq837gWtUhY3svG4TRq5cyDhNfmqD55WqD8ZsIosPBLDYL0LFi/rptupkO4t8Wcr3xfzbZOHrGC56+w+tmVOCwSu0pMPFlfdNKXwfj0RwjgnfOfVtw3kMGtcB+Iz92jIBA3l/CO0kVfs2LErcIIJYSWo4RTR2eYJaweNBldy31HIGiEUNeMaMH0xNuoMvM2n2kCGoj/QsQMrcgZRwOjVD/kVPfIVqmiLIlNSbjAI1J4cief8OUBIAECJVVwLcAUoYYzW8BJNkRiIWtOMpqPecr6QFGx/tAFjXj7FC26ROSLW5Amjq5UDgCdFFmIRWwWWOYJ7SrahRNmnmUnbiLPSz50QMDVmczCUnj8LWDkYRrh3nWGjh31h8qB72q+takpvjoLKtyfbMDhk+2iLqD8378m2nnvb89TnO3IXZcVt7umHK2lhXMwG6aEV+KPvV3YP0dWn/H5m9qtadWe2q1p1Z7ZrVnVntmtWdWe9dq71rtXau9a7X3rPae1d6z2ntWe99q71vtfau9b7UPrPaB1T6w2gdW+9BqH1rtQ6t9aLWPrPaR1T6y2kdW+9hqH1vtY6t93LVnFn2ZRV9m0ZdZ9GUWfZlFX2bRl1n0ZRZ9mUVfZtGXWfRlFn2ZRV9m0ZdZ9GUWfZlFX2bRl1n0ZRZ9mUVfZtGXWfRlFn2Zoi8NqGt+htYr/ESeEOrFBJtPKc8f5+tqrgyQOfOIWmRNF240aRZibby8qJu19HrJlTgj9BdCruS//0f+/9nQWmQuHbUXPX/bOGQuufDRwtNjyGnMqLs9BhhJIGxViq91JWD3uDUohqGpk8KFxhEMR6XBC3+H1t+R9Xfc/R0T628q/8bywljbSr0I5A/X/uHZP3z7hx48lj/U6JhmBT8i+0fc/sD72e0f1P7B7B+u/cOzf/j2j8D+Edo/IvuHDQFVEGAZOiVIux/M/uHaPzz7h2//COwfof0jsn/E1g9mQ8BsCJgNAbMhYDYETEGA3K04Tv541JWDZaTNytFsdsDKcYNgdOW4wcjS0Y17S2d8kDstnckgyh17tJZLvuc9KhKpLX2Mz30fDpW5vIXCwWOJQfWsh8DxEbYQKE+Zhvjbvg97PPBzPyL1Ie4jsuM2JuleTB7i9Zvy8N0Hqbu5cmeo6g4RHyppgXehHgulepADFji9oH7oke5fX8yoN4rlPQ0l4qdaaeyPwHVB9D/uNB3UtbHb3D16d2yr44+l8h1iG2x916vzcYdUQIx6kMl98zuaKVNfWSE0vXAOO4pmKuRjG+A9pSu2EdOdg8BLNOCL0rgZjLsI7F/ljbGPSVJJRhViNGh2t0TgyZ6GJx1rcV3VWBwFcNBUacH7xUv2HHjs/vqgse4xucmeBgNaJz3WhEYSlVWK8kymKLcmfw9vMhAEnU5cZnRne69C3h56Gjg8wNqL6632gwA6PDqGoZAneS29XG0u9b6otl2fDo4i0L8BECw58OzHfd7pfuNhrmWH3bt6Z3d/20up1S6dQU66Jnhz7ix4IhbovLEvvF7fiKIeob/4KM8fMyevq6Xxj5vUdQNHz9tjvuiyMdHvhIhZ8gOxOGw9nsq/S8ZIUS/FpOmyWGDFBhU/0Um7RjsH34vSOExb5MpANb0yU9hJeXGtMjsQx5mo5XY6y7Ek0QwVBxKCDcBhv+FJTlHugtws5YKtqwr3t8a9urxciPewdG94OcvE+1lzw2/Ecgam0aWC8HIbQll8SaVkq7AGRJhIvTxLKKE5jUUk4iTNAzwXF4IlGIlAcj9LAfQgyzC4IIkjhkWdo9zneeqpkEWtWoBo4Yvqujd3FchlRa0p3XP4Xp4CCVUZYvzdHB7o05VWSRlvmdnRaxPDbUW5jbXrIucm3magG5WNksMI+c64kvvG71nIeQ2Cew2Cew2C+/yD4CbX+JiQ2xnOuzuU7jU47TU47YDgtPuHhctcH1HiidytySWQnNcqJ7BiyAW9QHsbdLDVolovigQeuhcUjHjU1JJ0UQjsERuqlmWSY405fOZfUHKBaUJgWaxwkbIL7yKQ1nuZ8Ub2RC5c+WCF9SoXC9kolB2tbnkNMOMTH5oReehbyH5g9FACgMZ+VWtA3QumVdBGCodGPcYhYbKwPOYqnKBToBI3JAGjAayaUPhREiVhSpKMARu5metFrhcSL2cxoWmUJFwAMeIwTIHfPRH7BKeC3WoEt90a9Y+TNM9gjcLS4YTTNAYSw5BenEZ4KW0Qk5yHoZtxFgPLUg+WaRLDukeFo65+E6WOWWo7DhNY27DeYkGBU2hCfDcPgzgSHGYgMs9PYYWnrk9TP2Y0zrLUTd3IC/0g8XI/R4XvutA1C85EACyaRgyXXhazkMK/xEu8JAcoksSHF1keJIjmYokqYlZgmAyqsBKeK0BB4AJykiwNWOYCHiOPZnlC4ZEfizwkMYoYP2PCywGvUeylIcuE73tRIjLseFuB0k8stQms1mukZJJnYZaFbiCyOIhzkF1BFoDA47B4s5ScKQ8SKvdFXqDAsB15NLqi3hUN/ufsuGpXU/yG7j+QODCXTV3cW+G/tCH6chyeywE0X3awXILZDBZ4Uq3n2Ks68Z+vbkAFRltkPlTZ5tN1eudzc0/QxUqFcqMppuSFtIRUmGFLqCBmIudxkvtgd+QpC5MsjARsIrDNRDxI9xLKpVee90qoBxBqPhcfUcaiF0wGyNwUDVZmOoyALqgcqZ+EAc0DKrI0D0MGC87LiB/C/ngYAZ9qpQW+675sAq4q9PITQg6jHuwyPA1JAkIxYEyASkR9UMxA/4FNzffj/dRjV5Q82fKj5CVSr5ZOxes58w9cc0nqonYAGiLzQZeNo5xkNAKixymPvZgesruxp6JawMIXJDT1/X6H0YlEJPA4GGYu6v+RCF0vdwVYV4HgxE+Tg2Sj/0R0iqKAvDg6PWxv80A1jkAfoXmapxzM1Vh4YE6jGU1ZlLgH0Y+9rrPHod8dtzY3DEUcxSAPE85I7LM4TwhYN76bZl6W8xNbfOQlEu/uO5sbuGni5lEIGkicBUkUEpbSAMxjHgTZPn0khmUAm9sdiHZPT/QRNZIxiO5PuNVi00hamfqo86kxjq5rgnEQelFAKfHyPM5TjzHXCz0vyFiSEpHup61/RZ6Qtoz5p0Rb+FxG7sCnhpb6ULV5cqK+Hbheet5sddqFh8zyNHXJyyLH2KNDUCkybtBpnZ9+ecDp6aUc7cupQ9tLA8bFPxvp7zfJG5a/zCc8CdMkz10/5WkquAeGEGV5lgs/JQEIIPhFPZ/kOac8zyNGfUFCP4lTN/NVyM4/TYGRcg3CDwti51UtcBrvBJZ4JoMz/fRGpO9MoXzrULN3tEDG3tkHqW1qnSnYsf1QXN+2iXaGOU6ENABHelOU4rJdEkNijRQlHIsFUIk2/TzLPZVpzkcTMe9cR8i+nghPgf7ypa+C0MwtLz1v+1++BDYCWegGXiT90rhsqO+CRAxp6IEJzphHPVQJ2rEHDvl7e/LlrQv6cOlhSHprV2Y8NQ7CLWLWl2IaHy3Td459TliYRz4Lk5z5uZeJNPRBZaQR9eMkzDzQHxOPRGkciIiC4RbkJMLTJWgkQhm40UaUyBQuFT+FYZU65fEEENMHEM9oTmzt9wDckgBTvv8Ge8uLjyc6DQ2k3BrkkxH2w+NHNwRNlyP7wf+lqU+zNGMxsJ3r+14QkixhoP2KJM6ZS0Xmej7HM1qXZB49MmuvqzXokT3Z8skWLs1AIJkblvpbm3o30tfgXa9D6MlCk5+wNIpDlrsMLDvGWUyijPvUdanL0hgsqCzlXhxzFw/j8jxPMsBhlMJXfgLGugynQ0pPhmxh1OK8LYXWXVg12hjzUuXtEL/+3v9Qxntdm1A6fbHLmbVB/GKi6CwOOnfUlgJ/gDQvMvUnbh4qFG8JSjSWclOJsIK/w+A8kMpd7qZYqrPVr1XSqQpHgh5u22tjZDyeTJ8dQmcyUlFb356LKqcDjak9i5/0U/Vtd7GWDOZrrAvDDGB/kxMZmXM7lXPHxAsjGjalyZwthEkX1eC22MB4Q9Bub4qkWMtrv/CtUYv3zoc9aD4a0ToP3OT625G2QGGQK3jAjenj6Q3sSfCsqkcu8rGIcxgt3MeAXVYpcbjTGQgOqKkKljYzW+NcppmrlN0FdLK4xa+WFcy8WAO0b8cjfQ3wVlBwayEsqvVaqbTtdTZbYgUWLa9Bkuhioi3jzhVUVr+omSCG5xifPB2VKYmgF+3Ue4VqPYJ9daV5r6Gxb4ZKpKrYu/iqDZe8rnnRJuikm3WV57qYjHrUXs+kICHnE9rtFFBgDqo7T9Dg14UUdEzRkn+cq6xsdVWnzsXv39BlHmJiNBrTsvSnqsugIKLj1MKtV9qQ8y6F/l2xWskoyNWmBlsS0fQGtNOmcdDxylVRAnkhp8nY1xeSYs6+knXWormwufyvQ6llXQU4CDpXU94K29SPVd660syWaO+2oZrjGxvW84Bdy1xntjVVeZkU9lGVQiIf24EhgubZ2Q921DyIsoWyB3A4Tb5JbkJ69O6bUjLhILa1Ckv2eLZlyhtYmUu+6jHtIAtkvETNEdnaAvrEefqbj/iHVQkTJaMY1L4wHL5pZEEKtcGj/Lc2wcfk8CmKPR/bO+qKXcci7DQfbrP720OZSHaGRUoMlPZ+M05o1AVv52ptWH6WkQ1Il4/QFJM64a9W5lbnNLhHTXmTfNcLP4dZKd+O+ok1hrE5XugqhwKsSlevvLQ1uZX1VKwkswsZRLewb1qUP63rFacK16te26Iu1UJosqqaGQoedX0iesiabVR/uLmdF+haAoRjus7ZzyrhpDGrQ1/ArCFFidZh0nK63P22pTuiEsaShUicRZWq3WeARrxMGmSHuTgacA7TwHYpBwUo4/V98Nze9zSOabmmzh6E7x/rCiunAL4/4p6DyWK38rZb8XHtyDv/Wq3TyQp+XVbyll2+1neB6xt0YQU4UsAPaLTlDDs608OEcOYS8wtQr1Gz1VcT2pRDgFV+j/xp4JSVhIRzAzYEKpK3Q6LRAN1sPbpt32T/hMvlyOSzXJf3qfd/R8rhuUGjUwfRwpNl0OS983p/M7oflga07DisH2SMpPusMuvOgT0k0gJ/VqobMC8d2EiKvL3h+XTIpsvVPyXRlgOD/ZVEu0g0dZHA8Sn2kwArXlaoM8PKJSavDNYAqYW3rnDvSvG6Y6HfFMqBZFOPRUOBSF0W0DhiLg1dzOf4I5Bz9/0PT7AMcXyloBgattR9NI3lOKQeKDGfCcH3XunxbAvZQIaFFMvXFf1gAk9eyfL8FFb1Sl9JfE8S2/6Po9slfzW1aQFugx50Wy6K34T08SlQrEOMz9Yw1/cTnaiph9BNG3jPi+QjM/zWjVFHJ9HP8oipPcFqxNpi8M6+k1VSroUOf5HBUAt49c+qKLdkl0yW79MoiMHyjuE/ruv5ocdeEs26S72OLqG2j3lVPfKOYDWW+ZFCDAuYI+XMMQ1SzlDxv958AYol1nLuW4CGC0yt3j/U2uvfyfZUC0+P+uBFdy+F4TNfc09Mqu3V9kqpvZSaus7w6ET7uxrKJpdUzQFo5QgzK89cX4GTXVTXRfrHJtjkPZPHX2bKzdHV4tIXQ5h6+0ZdNITToLVmlYp6ESrqBqb3uvAWz6KVqOX1qpQ8igVsXep6dEp+z5do6b531JCOvMECnny4EaVeXZbJNqRDgGWUepRwacxoxDxKPAZ6P/Nfqqmmrth9Kj1EzqFc27cotjKwu5sEVhaGFRiRKGDKxbWMYMfYFb3n/aHWUnsF8lMRqh/yej9t8UVTpBeednyqmBACCe5IzA3uSvBLp+M9OiUeIRjkTZneVHXTXQtlwq62TrvGizw/gcfPDIxbd5UrXD/aAdcRojtOP0RnkM01QkNT+v2xiKizjbUmp0a2YiOVWm62HCwynyyK5saQsePJx15ALQgPo9dXSuaComkmun8ZTS+gR0b+1/JcSGcdoPJV4DVweMNaW825A0vHYx4T0+ePsEAORvgwMfTJlN42vOxeqq/q00K5ejDEeRuRrFCuGedUN2qAJ+PNTVLxOpu/WxW7sizsSO220jw7h5dOWwO7lfIy8aTu7cBTheXfFWWmUnDb294AEhUYb4f2YqmBRCyGccrNZKywPraVvN5VcFyJC7vXt+1Ng1M5YyMgH5oGMxah3RZQV2F0ktT6wFZPU1dBV33ciRp4w6Fp7sjSksgrVQM8w3xHf7OHDoOL91pSDJ4bWnzV3gFwRyIM+tsO2D4lymzddMD8O5IG8A+aEgu6dajb6Xw4uUj2kEYXFB6konSLZfS1IdTP8u0wj2U/0XTqzxxoAQsO5MSFShK9UMOdPOlyLKmvNjlNO3IRB9R3I8/8f3BHWn5tLo1tt7pOb1L1nQfXzbZpU7gYcY/prvDcQe6uZIqVitFSe/StIfaPFjztywfQ2u6lu0bhJMjcXonRrybjjhSN8T7dkdB/01cS24vG4WldNVKgcpkkZy3lAh9fuP+2h7D9TMCWolrb2CLm9/D8keg4SIz87Bbu4Coz/65S+FtMngW2mGHKbLaR6f1rnRKWFitlsAIViRTWUrfBTvfQs9C9ztsee3RtX0utq9+o3UaN5jaTjZxeowcQXOX7nTpZiVRE8zlgqpqjOgvt/iKjiZz/rUqJX4DJxP8DNZr//X//Uf7Ey2vxbZmJj1cOjujoxP5zIBxYq/Ao+kf5tUy91yvzT7JUgaUF/fnqH6XzvxzHUQqMM/3P91U5k0tQZnI5zteo6DvOP8rZbOY4M/nPjs9nvX/0b/wcYHUcnYg2/bmcHt6kjgSA32AC4WP4nOLnJvvq0M9lLpP8nGFnvcSgkc99z7O/tkZ34T8mMeVg4HXwInzuyc9RQjvOPT734ddo8L79Od4YN/55AL92BIvv+zyEX7tDj3d+Htmfjwe27vo8lmxjIhXvzjbAdjL6znHuxXXAdv0ItpHP8XrYic+B7XSMxb1GB7azYnjGPx+izvrcM6NPf73rc2C70ViHAz8Hths/eT/s81CPfk/CAdu1J41Tn1MvcCc+j/t0ByPuLqMz4Dp1NnMv4BlwXefkvvvnzHFG3eWHyTrmGrprN+kdR/d6o4/PYPJz6VdqrowA+FPw53Mlxf9E4S9o9ica/fkf5VIs0R20aUCQXzn0gjp/+/d/lMpVtlrwW6sM26gGoJu1+/1E0rYsyIvcqy6uwLR+3QuBL1QlAWOIYiRAv9jHRPI+FkKxuvImcrrvWKukrFQxQ9XHAxUf42uyKyONajxo6t2IxVixE5gC9FGgoi2T3tGKTJsdl9G1d0F2t45qCHrgWNXiyASa9M2Pd+rnIP3vsJl3F7LeAQIEAe8y2VfTaWS6xkFa7LoiUTpeSgEi2DEFC7oQaTlPqffj3VALkV1LoS16tQ7slw1wfKnoqT3F1Vrp5t9XzrVJO2jbz9DhrnVRNDiMV+gL+KtJ62Ilcza0N/Wbr99gG1CXi+zcSbpySei1BsUWBQTMBENpSukcBltm7ajqHjP+HjQNnhSyfku9Wcgjmx+//cUZXu84iMpJwI7YNDrSyq4/pfF3LqsRwYCqgJMC9QJNjdFVvkkWOi9gvuDX8rbgQ5hq65pJvE4X2m5kwYpe3axzx9wkCn/iOTuaAu3tl7KCRyULgJhaU2P1m3aJqOmV2hVjuXc1yvPJZNTdWY17U+D2p1DZGTg6a2QrR6ELgO9FUPdidKfCQCejDU34mh0AtR1y04Z0TF1l3Hu+pyzm24N3uvvsZf1dwpRumataMVObx+vVpK9Xk75eTfp6Nenr1aSvV5O+Xk36ejXp69Wkr1eTvl5N+no16euNl69Xk75eTfp6Nenr1aSvV5O+Xk36ejXp69Wkr1eTvl5N+no16evVpK9Xk75eTfp6Nenr1aSvV5O+Xk36ejXp69Wkr1eTvl5N+no16evVpE99NelW1tWOKww18Lve20m6KtzqTL+x83vx3E9XSZOKqsrom7elEiw5PNzn8Io13bwW/9oU/eayNgFobkblaJ9/ekB+mBXK+dWbv3/z5hdkLxPRe/aDua9STc0BTT0H5dAEZmL5AKVW6fhYq871TjT+VebQ4V65KQuQ1+1FkC0uVV5cH5Vtzh0qV71plagYAzthnKNElEzV7Ld6JCz9+3c/fPWf3/zUQ9MvPUxUGOwro14lxR3uaPDwHtADkPO3weWYLU76yaE9JuMf5S18e4rytEyl2qnoyuNxD6LlBmwOEFEmklomTyCAGLEcehfhvx2AkK9UCQ1MZFNVb2SgtdZOOvRYT23cJAtevpuryiRNV4lEBWHPMasfBPmiNS3V+6KEnaEATus/Hm39SAgElpmbhOUeGv/emzMizrrHcaHu/MS4/ra06tZNxF1c7AHY/qUta8UVDntI7h7aOF5gmDFsRNd8pSPHYd/CijdL2DN5aT33fHysbzkcq0C2aaQZKVuYOypDdjwm/U6B7gCIzp8Aagfh/LOzBGjqQuJXfExBY29U1Vo5H4Ma50+er9rfCa/2LaIdYrunNmbbGFxY4c1WtTZTZadDlLzJs/VxxDPq/kLIlfz3TN7WKd9RMiP+jFD73aYE3RljZrp7IR8J6z+++fnnHs6/Mpd51ptSbyYdTIBnMHivb5xuCgdgV2/MWV3kaywllxcLrLbowDhjm/RcNtzC9aaU1yBrLU7qnQdH9+qOb3hzY4XRvgbyvQbyPTyQ79OeEPRHkIP/0evTKHxYVk5lJpVSBqpEmysncozsMS2tQqi6uoqpvHXA6n1Twx62FFgNSzt1CjFQfnjbZN5rYi9gzDqa65oPIFnUXSwSQfimmXfVDh5Ntk3u2nZWGd+a3q2dU3YAgv5DuX71jdfS98rrgf5jMnOstzZyJjMxj6gYj2f24dxN3piS/sPy0qqSuHiPFXZ1YpkqhnbQPcUdJIeWyFAugXlRNugi32UH8vdChq/+sBLK2sGaaoDFVMKPWUhfOIN7pks9+5l1B3s30xoWD9hCg5uoe1ZfzwbaMiNZ0FmNu21LXcTK+rTbtnplp0YrMI27YBXGelurtrr3lcXaVzTld3XHupyMzli1DSB9fbbJ0b1nHazp8ihiqWKXD64LNlpTxdzc/Q0mvAKZ9QxQM+lsecMw8iL7Zpc0eHLuO+jy+h5/GpV0oMBDqzKb1Eu1H79fNVLxQDsk7qVm0Cvvk0R4vZ5QZw9hV5UM2KvdZSrsHVzKaYRJ26+3ONQur3d2fkAxrwPYs1WlmxUHntypRpvKWCHrdm+Z5qzIdDATf7iR23uvyCMIdOjy8+bdtjqn9iNNnBX1u7UOjnQi7Nvzfk9z5ePSfhkwiw9hzq4H4wkb1rIyz+/AoofLTF2Waj//oY/H4HAmr5boapyqSlkbrG7ZlnVSpXRB478g/9ZqiJYXcC8T/iTrU1u1wVp+MEX8lKCWFfaxvClHj5d2vekSBl3h2R9KdfNdgTcvr/q3NM96HG7uxQAqGaltLtJQ7bRuplFq36pxrqsY2Nc7t/n47Q5s0q6vuhybC3UAMQOjb6ZUlJmZ7eV7+xxqxC0vhcyUu7tLeFXNfpWPmf/2vF9GVGoID1EOe8C0o3zCxHT0M5R8KXO4J85ZZCLe5PH5QWjTumgPXaNHFgcC9On/A37I7rk="

import base64, json, zlib
import numpy as np
import pandas as pd
from IPython import get_ipython

_IPYTHON = get_ipython()
if _IPYTHON is not None:
    _IPYTHON.run_line_magic("matplotlib", "inline")

import matplotlib.pyplot as plt
from IPython.display import Markdown, display

PAYLOAD = json.loads(zlib.decompress(base64.b64decode(_PAYLOAD_B64)).decode("utf-8"))
SUMMARY = PAYLOAD["summary"]
OVERLAY = PAYLOAD["overlay"]
CONTRACT = PAYLOAD["contract"]
PROVENANCE = PAYLOAD["provenance"]
FRAME_URI = PAYLOAD.get("frame_uri")
MANIFEST_URI = PAYLOAD.get("manifest_uri")
EXACTNESS = SUMMARY["profile"]["analysis_exactness"]
TABLE_NAME = SUMMARY["table_name"]

PREVIEW_ROWS = 20
MAX_NUMERIC_CHARTS = 12
MAX_CATEGORICAL_CHARTS = 8
CHART_MAX_POINTS = 200000

pd.set_option("display.max_rows", PREVIEW_ROWS)
pd.set_option("display.max_columns", 30)
pd.set_option("display.max_colwidth", 100)
plt.rcParams.update({
    "figure.dpi": 120,
    "savefig.dpi": 120,
    "figure.facecolor": "white",
    "axes.facecolor": "white",
    "axes.grid": True,
    "grid.alpha": 0.22,
    "font.size": 9,
})

def metric(section, name, default=None):
    return (SUMMARY.get("profile", {}).get("sections", {}).get(section, {})
            .get("metrics", {}).get(name, {"value": default, "exactness": EXACTNESS}))

def metric_value(section, name, default=None):
    return metric(section, name, default).get("value", default)

def bounded(value, chars=900):
    if isinstance(value, (dict, list, tuple)):
        text = json.dumps(value, sort_keys=True, default=str)
    else:
        text = str(value)
    return text if len(text) <= chars else text[:chars] + " … [bounded display]"

def show_metrics(section, limit=30):
    rows = []
    metrics = (SUMMARY.get("profile", {}).get("sections", {}).get(section, {})
               .get("metrics", {}))
    for name, item in sorted(metrics.items()):
        rows.append({
            "metric": name,
            "value": bounded(item.get("value")),
            "unit": item.get("unit") or "—",
            "n": item.get("denominator") if item.get("denominator") is not None else "—",
            "exactness": item.get("exactness", EXACTNESS),
        })
    display(pd.DataFrame(rows[:limit]))
    if len(rows) > limit:
        display(Markdown(f"*Displayed {limit} of {len(rows)} metrics; the complete machine payload is in `summary.json`.*"))

def interpretation(text):
    display(Markdown("**Interpretation.** " + text))

FRAME = None
if FRAME_URI:
    lowered = FRAME_URI.replace("\\", "/").lower()
    assert not any(marker in lowered for marker in ("/gold/", "gold_weather_z", "model_ready", "model-ready"))
    assert ("/eda/silver/" in lowered or not lowered.startswith("s3://")), FRAME_URI
    import pyarrow.parquet as pq
    FRAME = pq.read_table(FRAME_URI).to_pandas()

import html, io, re
from IPython.display import HTML
from leviathan.eda.reader_charts import (
    chart_scope_record as _reader_chart_scope_record,
    compute_chart_payloads as _compute_reader_chart_payloads,
    render_chart_payload as _render_reader_chart_payload,
)

PROFILE = SUMMARY.get("profile", {})
SECTIONS = PROFILE.get("sections", {})
OUTPUT_QUARANTINE = TABLE_NAME == "silver_model_predictions"
READER = {}
for _reader_payload in (PROVENANCE.get("reader"), SUMMARY.get("reader")):
    if isinstance(_reader_payload, dict):
        READER.update(_reader_payload)

FULL_DISPLAY_MAX_ROWS = 200
BOUNDED_PREVIEW_MAX_ROWS = 40
MAX_READER_CHARTS = 4
MIN_TREND_POINTS = 8
MIN_SCATTER_POINTS = 20
MIN_INSIGHTS = 3
MAX_INSIGHTS = 10

pd.set_option("display.max_rows", max(PREVIEW_ROWS, BOUNDED_PREVIEW_MAX_ROWS))
pd.set_option("display.max_columns", 40)
pd.set_option("display.max_colwidth", 120)
plt.rcParams.update({
    "axes.spines.top": False,
    "axes.spines.right": False,
    "grid.alpha": 0.18,
})

def first_value(*values, default=None):
    for value in values:
        if value is not None:
            return value
    return default

def as_list(value):
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    return [value]

def text_items(value):
    items = []
    for item in as_list(value):
        if isinstance(item, dict):
            item = first_value(
                item.get("insight"), item.get("statement"), item.get("text"), item.get("message"),
                item.get("finding"), item.get("title"),
            )
        if item is not None and str(item).strip():
            items.append(str(item).strip())
    return items

def humanize(name):
    return re.sub(r"\s+", " ", str(name).replace("_", " ")).strip().capitalize()

def display_value(value):
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return "not assessed"
    if isinstance(value, (np.integer, int)):
        return f"{int(value):,}"
    if isinstance(value, (np.floating, float)):
        return f"{float(value):,.3g}"
    return bounded(value, 180)

def rate_display(value):
    """Format rates without rounding a real, small issue down to zero."""
    if value is None or pd.isna(value):
        return "not assessed"
    rate = float(value)
    if rate == 0:
        return "0%"
    if abs(rate) < 0.0001:
        return f"{rate:.6%}"
    if abs(rate) < 0.01:
        return f"{rate:.4%}"
    return f"{rate:.2%}"

SOURCE_SHAPE = READER.get("source_shape", {})
if not isinstance(SOURCE_SHAPE, dict):
    SOURCE_SHAPE = {}
READER_SOURCE_SHAPE = SOURCE_SHAPE.get("source_shape")
READER_ANALYSIS_SHAPE = SOURCE_SHAPE.get("analysis_shape")
PROFILE_ROWS = metric_value("schema_contract", "row_count", None)
SOURCE_ROWS = int(first_value(
    READER.get("source_rows"), SOURCE_SHAPE.get("source_rows"), SOURCE_SHAPE.get("rows"),
    READER_SOURCE_SHAPE[0] if isinstance(READER_SOURCE_SHAPE, list) and READER_SOURCE_SHAPE else None,
    PROVENANCE.get("source_total_rows"), PROFILE_ROWS,
    len(FRAME) if FRAME is not None else None, default=0,
) or 0)
ANALYSIS_ROWS = int(first_value(
    READER.get("analysis_rows"), SOURCE_SHAPE.get("analysis_rows"), SOURCE_SHAPE.get("analyzed_rows"),
    READER_ANALYSIS_SHAPE[0] if isinstance(READER_ANALYSIS_SHAPE, list) and READER_ANALYSIS_SHAPE else None,
    PROFILE_ROWS, len(FRAME) if FRAME is not None else None, default=0,
) or 0)
ANALYSIS_COLUMNS = int(first_value(
    SOURCE_SHAPE.get("column_count"), SOURCE_SHAPE.get("columns"),
    READER_ANALYSIS_SHAPE[1] if isinstance(READER_ANALYSIS_SHAPE, list) and len(READER_ANALYSIS_SHAPE) > 1 else None,
    metric_value("schema_contract", "column_count", None),
    len(FRAME.columns) if FRAME is not None else None, default=0,
) or 0)

def declared_column_names():
    names = []
    declared = as_list(CONTRACT.get("physical_columns")) + as_list(CONTRACT.get("partition_keys"))
    for item in declared:
        if isinstance(item, dict) and item.get("name"):
            names.append(str(item["name"]))
    names.extend(str(name) for name in (metric_value("schema_contract", "observed_columns", []) or []))
    if FRAME is not None:
        names.extend(str(name) for name in FRAME.columns)
    return list(dict.fromkeys(names))

ALL_COLUMNS = declared_column_names()
VALUE_COLUMNS = [str(value) for value in as_list(CONTRACT.get("value_columns"))]

def row_meaning():
    configured = first_value(
        READER.get("row_meaning"), READER.get("grain"), OVERLAY.get("row_meaning"),
    )
    if isinstance(configured, dict):
        configured = first_value(configured.get("description"), configured.get("text"))
    if configured:
        return str(configured)
    natural_key = [str(value) for value in as_list(CONTRACT.get("natural_key"))]
    if natural_key:
        keys = ", ".join(f"`{name}`" for name in natural_key)
        return f"One row is identified by {keys}."
    return "The registry does not declare a complete natural key; inferred grain is evidence only."

def _stable_hash_order(frame):
    if frame.empty:
        return frame
    text = frame.astype("string").fillna("<NA>")
    order = pd.util.hash_pandas_object(text, index=False).sort_values(kind="mergesort").index
    return frame.loc[order]

def _parse_reader_time(series, name):
    if pd.api.types.is_datetime64_any_dtype(series):
        return pd.to_datetime(series, errors="coerce")
    if pd.api.types.is_numeric_dtype(series) and "year" in str(name).lower():
        years = pd.to_numeric(series, errors="coerce")
        text = years.round().astype("Int64").astype("string")
        return pd.to_datetime(text, format="%Y", errors="coerce")
    text = series.astype("string").str.strip()
    parsed = pd.Series(pd.NaT, index=series.index, dtype="datetime64[ns]")
    formats = (
        (text.str.match(r"^\d{4}-\d{2}-\d{2}(?:[ T].*)?$", na=False), "%Y-%m-%d", 10),
        (text.str.match(r"^\d{4}/\d{2}/\d{2}(?:[ T].*)?$", na=False), "%Y/%m/%d", 10),
        (text.str.match(r"^\d{8}$", na=False), "%Y%m%d", None),
        (text.str.match(r"^\d{4}-\d{2}$", na=False), "%Y-%m", None),
    )
    for mask, date_format, width in formats:
        if mask.any():
            values = text.loc[mask].str.slice(0, width) if width else text.loc[mask]
            parsed.loc[mask] = pd.to_datetime(values, format=date_format, errors="coerce")
    remaining = parsed.isna()
    years = text.loc[remaining].str.extract(r"((?:19|20)\d{2})", expand=False)
    parsed.loc[remaining] = pd.to_datetime(years, format="%Y", errors="coerce")
    return parsed

def _time_sort(frame):
    configured = as_list(READER.get("time_columns"))
    configured += as_list(READER.get("primary_time_column"))
    chart_plan = READER.get("chart_plan")
    if isinstance(chart_plan, dict):
        for chart in as_list(chart_plan.get("charts")):
            if isinstance(chart, dict):
                configured += as_list(chart.get("columns"))
    configured += as_list(CONTRACT.get("natural_key"))
    candidates = [str(value) for value in configured if str(value) in frame.columns]
    candidates += [
        str(column) for column in frame.columns
        if any(token in str(column).lower() for token in (
            "date", "year", "month", "week", "season", "time", "as_of",
        ))
    ]
    for column in dict.fromkeys(candidates):
        series = frame[column]
        parsed = _parse_reader_time(series, column)
        if parsed.notna().mean() >= 0.8:
            return column, parsed
    return None, None

def deterministic_preview(frame):
    if frame is None:
        return None, "No frozen analysis frame is attached to this notebook."
    if len(frame) <= FULL_DISPLAY_MAX_ROWS:
        return frame.copy(), f"Full DataFrame: all {len(frame):,} analyzed rows are shown."
    pieces = []
    time_column, order = _time_sort(frame)
    if time_column is not None:
        ordered = frame.assign(__reader_order=order).sort_values(
            "__reader_order", kind="mergesort", na_position="last",
        ).drop(columns="__reader_order")
        pieces.extend([ordered.head(10), ordered.tail(10)])
    entity_candidates = [
        str(value) for value in as_list(READER.get("preview_strata"))
        if str(value) in frame.columns and str(value) != time_column
        and frame[str(value)].nunique(dropna=True) <= 50
    ] + [
        str(value) for value in as_list(CONTRACT.get("natural_key"))
        if str(value) in frame.columns and str(value) != time_column
        and frame[str(value)].nunique(dropna=True) <= 50
    ]
    if entity_candidates:
        entity = entity_candidates[0]
        grouped = frame.sort_values(entity, kind="mergesort").groupby(entity, dropna=False)
        pieces.append(grouped.head(1).head(20))
    pieces.append(_stable_hash_order(frame).head(BOUNDED_PREVIEW_MAX_ROWS))
    preview = pd.concat(pieces, ignore_index=False)
    preview = preview.loc[~preview.index.duplicated()].drop_duplicates()
    preview = preview.head(BOUNDED_PREVIEW_MAX_ROWS)
    policy = (
        f"Deterministic preview: {len(preview):,} of {len(frame):,} analyzed rows; "
        "earliest/latest, entity examples, then stable-hash fill."
    )
    return preview, policy

def safe_preview(frame):
    configured = READER.get("preview")
    if isinstance(configured, dict) and isinstance(configured.get("records"), list):
        preview = pd.DataFrame(configured["records"])
        policy_value = READER.get("display_policy")
        if isinstance(policy_value, dict):
            policy_value = first_value(
                policy_value.get("description"), policy_value.get("mode"),
                default=bounded(policy_value, 500),
            )
        displayed_rows = configured.get("displayed_rows") or len(preview)
        policy = str(policy_value or (
            f"Reader evidence preview: {displayed_rows:,} "
            f"of {ANALYSIS_ROWS:,} analyzed rows; {configured.get('mode', 'bounded')}."
        ))
    else:
        preview, policy = deterministic_preview(frame)
    if preview is not None and OUTPUT_QUARANTINE:
        preview = preview.copy()
        for column in VALUE_COLUMNS:
            if column in preview:
                preview[column] = "[quarantined output value]"
        policy += " Output-plane value columns are masked."
    return preview, policy

def _configured_column_dictionary():
    configured = first_value(
        READER.get("column_dictionary"), READER.get("column_descriptions"),
        READER.get("columns"), default={},
    )
    if isinstance(configured, list):
        return {
            str(item.get("column") or item.get("name")): item
            for item in configured
            if isinstance(item, dict) and (item.get("column") or item.get("name"))
        }
    return configured if isinstance(configured, dict) else {}

def _column_description(column, configured):
    item = configured.get(column, {})
    configured_why = READER.get("why_it_matters", {})
    if not isinstance(configured_why, dict):
        configured_why = {}
    if isinstance(item, str):
        return item, str(
            configured_why.get(column) or "Supports interpretation and feature review."
        )
    if isinstance(item, dict):
        meaning = first_value(item.get("meaning"), item.get("description"), item.get("text"))
        why = first_value(
            item.get("why_it_matters"), item.get("feature_relevance"), item.get("role"),
        )
        if meaning:
            return str(meaning), str(
                why or configured_why.get(column)
                or "Supports interpretation and feature review."
            )
    lower = column.lower()
    if any(token in lower for token in ("date", "year", "month", "week", "season", "as_of")):
        return (
            f"{humanize(column)} used to place observations in time.",
            "Controls ordering, lagging, and cutoff safety.",
        )
    if column in VALUE_COLUMNS:
        return (
            f"Source measure: {humanize(column).lower()}.",
            "Potential feature input; units and timing must be governed.",
        )
    if lower == "source" or lower.endswith("_source"):
        return (
            "Source-system or release provenance label.",
            "Supports lineage and source consistency checks.",
        )
    if lower.endswith("_id") or column in as_list(CONTRACT.get("natural_key")):
        return (
            f"Identifier or grain field: {humanize(column).lower()}.",
            "Controls uniqueness and safe joins.",
        )
    return (
        f"Source field: {humanize(column).lower()}.",
        "Retained for contract, grouping, or quality analysis.",
    )

def column_dictionary():
    configured = _configured_column_dictionary()
    declared = as_list(CONTRACT.get("physical_columns")) + as_list(CONTRACT.get("partition_keys"))
    contract_columns = {
        str(item.get("name")): item
        for item in declared if isinstance(item, dict) and item.get("name")
    }
    missingness = metric_value("missingness_validity", "column_missingness", {}) or {}
    vocabularies = metric_value("entity_vocabulary_coverage", "vocabularies", {}) or {}
    distributions = metric_value("distributions", "numeric_distributions", {}) or {}
    rows = []
    for column in ALL_COLUMNS:
        declared_column = contract_columns.get(column, {})
        configured_item = configured.get(column, {})
        if not isinstance(configured_item, dict):
            configured_item = {}
        meaning, why = _column_description(column, configured)
        if configured_item and any(
            key in configured_item
            for key in ("observed_dtype", "declared_type", "null_rate", "distinct_count")
        ):
            dtype = first_value(
                configured_item.get("observed_dtype"), configured_item.get("declared_type"),
                default="not observed",
            )
            null_rate = configured_item.get("null_rate")
            distinct = configured_item.get("distinct_count")
            example = configured_item.get("example")
        elif FRAME is not None and column in FRAME:
            series = FRAME[column]
            dtype = str(series.dtype)
            null_rate = float(series.isna().mean()) if len(series) else None
            distinct = int(series.nunique(dropna=True))
            examples = series.dropna().head(1).tolist()
            example = examples[0] if examples else None
        else:
            dtype = first_value(
                declared_column.get("target_arrow_type"), declared_column.get("arrow_type"),
                declared_column.get("glue_type"), default="not observed",
            )
            null_rate = (missingness.get(column) or {}).get("null_rate")
            distinct = first_value(
                (vocabularies.get(column) or {}).get("distinct_count"),
                (distributions.get(column) or {}).get("distinct_count"),
            )
            example = None
        if OUTPUT_QUARANTINE and column in VALUE_COLUMNS:
            example = "[quarantined]"
        reader_units = READER.get("units", {})
        if not isinstance(reader_units, dict):
            reader_units = {}
        item = configured_item
        unit = first_value(
            item.get("unit") if isinstance(item, dict) else None,
            reader_units.get(column),
            OVERLAY.get("units", {}).get(column), default="not declared",
        )
        rows.append({
            "column": column,
            "dtype": dtype,
            "unit": unit,
            "example": bounded(example, 80) if example is not None else "not available",
            "null_rate": rate_display(null_rate) if ANALYSIS_ROWS else "not assessed",
            "distinct": distinct if ANALYSIS_ROWS else None,
            "plain_English_meaning": meaning,
            "why_it_matters": why,
        })
    return pd.DataFrame(rows)

def dashboard_kpis():
    configured = READER.get("dashboard_kpis")
    rows = []
    if isinstance(configured, dict):
        configured = [{"label": key, "value": value} for key, value in configured.items()]
    for item in as_list(configured):
        if isinstance(item, dict) and "value" in item:
            rows.append({
                "label": first_value(item.get("label"), item.get("name"), default="Metric"),
                "value": item.get("value"),
                "detail": first_value(item.get("detail"), item.get("unit"), default=""),
            })
    cap = SUMMARY.get("decision_capsule", {})
    defaults = [
        {"label": "Source shape", "value": f"{SOURCE_ROWS:,} x {ANALYSIS_COLUMNS:,}", "detail": EXACTNESS},
        {"label": "Analyzed rows", "value": ANALYSIS_ROWS, "detail": EXACTNESS},
        {"label": "Disposition", "value": (cap.get("disposition") or {}).get("value", PROFILE.get("disposition", "not assessed")), "detail": "feature readiness"},
        {"label": "PIT status", "value": "eligible" if metric_value("pit_leakage", "feature_eligible_source", False) else "not ready", "detail": "cutoff safety"},
        {"label": "Candidates", "value": len(SUMMARY.get("feature_candidates", [])), "detail": "review only"},
        {"label": "Blockers", "value": len(PROFILE.get("blockers", [])), "detail": "quality / contract"},
    ]
    existing = {str(row["label"]).lower() for row in rows}
    rows.extend(row for row in defaults if str(row["label"]).lower() not in existing)
    return rows[:8]

def show_kpi_cards(rows):
    cards = []
    for row in rows:
        cards.append(
            '<div style="border:1px solid #d9e0e8;border-radius:8px;padding:12px;min-width:145px;flex:1">'
            f'<div style="font-size:12px;color:#52606d">{html.escape(str(row["label"]))}</div>'
            f'<div style="font-size:22px;font-weight:650;color:#172b4d;margin:3px 0">{html.escape(display_value(row["value"]))}</div>'
            f'<div style="font-size:11px;color:#6b778c">{html.escape(str(row.get("detail") or ""))}</div>'
            '</div>'
        )
    markup = '<div style="display:flex;gap:8px;flex-wrap:wrap">' + ''.join(cards) + '</div>'
    display(HTML(markup))

def ordinary_describe():
    configured = first_value(
        READER.get("ordinary_statistics"), READER.get("descriptive_statistics")
    )
    if isinstance(configured, dict) and any(
        key in configured for key in ("numeric", "categorical", "temporal")
    ):
        frames = []
        for section_name in ("numeric", "categorical", "temporal"):
            section = configured.get(section_name) or {}
            records = section.get("records") if isinstance(section, dict) else None
            if isinstance(records, list) and records:
                frame = pd.DataFrame(records)
                frame.insert(0, "statistics_section", section_name)
                frames.append(frame)
        if frames:
            return pd.concat(frames, ignore_index=True, sort=False)
        return pd.DataFrame([{
            "status": configured.get("status", "not assessed"),
            "reason": "Reader statistics contain no displayable records.",
        }])
    if isinstance(configured, list) and configured:
        return pd.DataFrame(configured)
    if isinstance(configured, dict) and configured:
        return pd.DataFrame(configured).transpose()
    if FRAME is None or FRAME.empty:
        return pd.DataFrame([{"status": "not assessed", "reason": "No analysis frame attached."}])
    allowed = [
        column for column in FRAME.columns
        if not (OUTPUT_QUARANTINE and column in VALUE_COLUMNS)
    ]
    if not allowed:
        return pd.DataFrame([{"status": "not assessed", "reason": "Output values are quarantined."}])
    return FRAME[allowed].describe(include="all").transpose()

def quality_scorecard():
    configured = READER.get("quality_scorecard")
    if isinstance(configured, dict) and isinstance(configured.get("checks"), list):
        configured = configured["checks"]
    if isinstance(configured, dict):
        configured = [
            {"check": key, **(value if isinstance(value, dict) else {"status": value})}
            for key, value in configured.items()
        ]
    if isinstance(configured, list) and configured:
        rows = []
        for item in configured:
            if isinstance(item, dict):
                rows.append({
                    "check": first_value(item.get("check"), item.get("name"), default="Quality check"),
                    "status": str(item.get("status", "not assessed")).upper(),
                    "evidence": bounded(first_value(
                        item.get("summary"), item.get("evidence"), item.get("detail"),
                        default="",
                    ), 500),
                })
        if OUTPUT_QUARANTINE:
            for row in rows:
                if "validity" in str(row.get("check") or "").lower():
                    row["status"] = "NOT ASSESSED"
                    row["evidence"] = (
                        "Output-plane numeric value validity is quarantined; schema, null, "
                        "freshness, partition, and duplicate QA remain in scope."
                    )
        if rows:
            return pd.DataFrame(rows)
    checks = (
        "Grain and duplicates", "Schema contract", "Required-field completeness",
        "Temporal coverage / cadence", "Validity / identities", "PIT availability",
    )
    if ANALYSIS_ROWS <= 0:
        return pd.DataFrame([
            {"check": name, "status": "NOT ASSESSED", "evidence": "No analyzed rows; a zero rate is not inferred."}
            for name in checks
        ])
    duplicate_rate = metric_value("grain_integrity", "duplicate_key_row_rate", None)
    missing_required = metric_value("schema_contract", "missing_required_columns", []) or []
    required_rate = metric_value("missingness_validity", "required_complete_row_rate", None)
    temporal = metric_value("temporal_structure", "usable_temporal_columns", []) or []
    pit_ready = bool(metric_value("pit_leakage", "feature_eligible_source", False))
    validity = None if OUTPUT_QUARANTINE else metric_value(
        "missingness_validity", "validity_summary", None
    )
    duplicate_evidence = (
        "No duplicate natural-key rows." if duplicate_rate == 0
        else f"Duplicate-key row rate: {duplicate_rate:.2%}." if duplicate_rate is not None
        else "Natural-key duplicate rate unavailable."
    )
    return pd.DataFrame([
        {"check": checks[0], "status": "PASS" if duplicate_rate == 0 else ("CAVEAT" if duplicate_rate is not None else "NOT ASSESSED"), "evidence": duplicate_evidence},
        {"check": checks[1], "status": "BLOCKER" if missing_required else "PASS", "evidence": "Missing required columns: " + ", ".join(missing_required) if missing_required else "Required columns are present."},
        {"check": checks[2], "status": "PASS" if required_rate == 1 else ("CAVEAT" if required_rate is not None else "NOT ASSESSED"), "evidence": f"Complete-row rate: {rate_display(required_rate)}." if required_rate is not None else "Completeness denominator unavailable."},
        {"check": checks[3], "status": "PASS" if temporal else "NOT ASSESSED", "evidence": "Usable axes: " + ", ".join(map(str, temporal)) if temporal else "No validated temporal axis."},
        {"check": checks[4], "status": "CAVEAT" if validity else "NOT ASSESSED", "evidence": bounded(validity, 500) if validity else "No source-specific identity rule supplied."},
        {"check": checks[5], "status": "PASS" if pit_ready else "BLOCKER", "evidence": "Source passed the source-level PIT gate." if pit_ready else "Knowledge-time availability is not safe enough for promotion."},
    ])

def computed_insights():
    configured = first_value(READER.get("reader_insights"), READER.get("insights"))
    if isinstance(configured, list) and any(isinstance(item, dict) for item in configured):
        # Reader-facing insights should be actual findings, not boilerplate
        # explaining why a configured analytical rule could not run.
        configured = [
            item for item in configured
            if not isinstance(item, dict)
            or str(item.get("status") or "evaluated").lower() == "evaluated"
        ]
    insights = text_items(configured)
    if not insights:
        insights.append(
            f"The evidence contains {ANALYSIS_ROWS:,} analyzed rows and {ANALYSIS_COLUMNS:,} columns; source coverage reports {SOURCE_ROWS:,} rows ({EXACTNESS})."
        )
        if FRAME is not None and not FRAME.empty:
            missing = FRAME.isna().mean().sort_values(ascending=False)
            if len(missing):
                column = str(missing.index[0])
                insights.append(
                    f"`{column}` has the highest observed null rate at {rate_display(missing.iloc[0])}; missing must not be read as zero."
                )
            time_column, order = _time_sort(FRAME)
            if time_column is not None and order.notna().any():
                valid = order.dropna()
                insights.append(
                    f"`{time_column}` spans {valid.min()} to {valid.max()} across {valid.nunique():,} observed periods."
                )
        duplicate_rate = metric_value("grain_integrity", "duplicate_key_row_rate", None)
        if duplicate_rate is not None and ANALYSIS_ROWS:
            insights.append(
                f"Declared-key duplicate-row rate is {duplicate_rate:.2%} across the analyzed frame."
            )
        insights.append(
            "The source-level PIT gate passed; each transformation still needs a cutoff rule."
            if metric_value("pit_leakage", "feature_eligible_source", False)
            else "The source is not PIT-ready; final/current values must not be treated as known earlier."
        )
    fallbacks = [
        f"There are {len(SUMMARY.get('feature_candidates', []))} review-only candidate(s); none is enabled here.",
        f"The registry declares {len(VALUE_COLUMNS)} feature-bearing value column(s).",
        "The analysis is source-only; no target association was calculated.",
    ]
    for item in fallbacks:
        if len(insights) >= MIN_INSIGHTS:
            break
        insights.append(item)
    # Five concise observations are enough to understand the source for feature
    # engineering; detailed evidence remains in the tables and sidecars.
    return list(dict.fromkeys(insights))[:min(MAX_INSIGHTS, 5)]

def notable_observations():
    configured = first_value(READER.get("notable_observations"), READER.get("notable_rows"))
    if isinstance(configured, dict):
        records = first_value(configured.get("records"), configured.get("rows"))
        if isinstance(records, list):
            flattened = []
            for item in records:
                if not isinstance(item, dict):
                    continue
                row = item.get("row") if isinstance(item.get("row"), dict) else item
                flattened.append({
                    "why_notable": "; ".join(map(str, as_list(item.get("reasons")))),
                    **row,
                })
            configured = flattened
        else:
            configured = []
    if isinstance(configured, list) and configured:
        return pd.DataFrame(configured).head(12)
    if FRAME is None or FRAME.empty:
        return pd.DataFrame([{"status": "not assessed", "reason": "No analyzed rows."}])
    if OUTPUT_QUARANTINE:
        preview, _ = safe_preview(FRAME)
        return preview.head(4) if preview is not None else pd.DataFrame()
    time_column, order = _time_sort(FRAME)
    selected, labels = [], []
    if time_column is not None and order.notna().any():
        valid_indices = order.dropna().sort_values(kind="mergesort").index
        selected.extend([valid_indices[0], valid_indices[-1]])
        labels.extend(["earliest observed row", "latest observed row"])
    measures = [
        column for column in VALUE_COLUMNS
        if column in FRAME and pd.api.types.is_numeric_dtype(FRAME[column])
    ]
    for column in measures[:3]:
        values = pd.to_numeric(FRAME[column], errors="coerce")
        if values.notna().any():
            selected.extend([values.idxmin(), values.idxmax()])
            labels.extend([f"lowest {column}", f"highest {column}"])
    if not selected:
        selected = list(_stable_hash_order(FRAME).head(4).index)
        labels = ["deterministic example"] * len(selected)
    rows = FRAME.loc[selected].copy().reset_index(drop=True)
    rows.insert(0, "why_notable", labels)
    return rows.drop_duplicates().head(10)

def _measure_columns(frame):
    entity_axes = {
        "commodity_code", "country_code", "entity_id", "source_unit_id",
        "state_code", "region_code", "series_id",
    }
    time_tokens = (
        "date", "year", "month", "week", "season", "period", "as_of",
        "time", "survey_number", "fortnight_seq",
    )
    def eligible(column):
        name = str(column)
        lower = name.lower()
        return (
            name in frame.columns
            and pd.api.types.is_numeric_dtype(frame[name])
            and lower not in entity_axes
            and not lower.endswith(("_id", "_code"))
            and not any(token in lower for token in time_tokens)
        )
    preferred = [
        column
        for column in text_items(READER.get("primary_measures")) + VALUE_COLUMNS
        if eligible(column)
    ]
    numeric = [
        str(column)
        for column in frame.select_dtypes(include=[np.number]).columns
        if eligible(column)
    ]
    return list(dict.fromkeys(preferred + numeric))[:MAX_NUMERIC_CHARTS]

def _chart_scope(plotted_rows, chart_exactness, scope):
    return (
        f"source n={SOURCE_ROWS:,}; analyzed n={ANALYSIS_ROWS:,}; plotted n={plotted_rows:,}; "
        f"exactness={chart_exactness}"
    )

def _scope_prose(scope):
    if isinstance(scope, dict):
        skip = {"analysis_rows", "exactness", "plotted_rows", "source_rows"}
        parts = []
        for key, value in scope.items():
            if key in skip or value in (None, "", [], {}):
                continue
            if isinstance(value, (dict, list, tuple)):
                continue
            parts.append(f"{humanize(key)}={value}")
        return "; ".join(parts) or "complete canonical source aggregate"
    return bounded(scope or "complete canonical source aggregate", 500)

def _chart_unit(measure, configured):
    unit = str(configured or "").strip()
    if unit and "verify" not in unit.lower() and "source-native" not in unit.lower():
        return unit
    name = str(measure).lower()
    suffixes = {
        "_mm": "mm", "_pct": "%", "_percent": "%", "_mt": "metric tonnes",
        "_kg": "kg", "_ha": "hectares", "_c": "°C", "_kt": "thousand tonnes",
    }
    return next((label for suffix, label in suffixes.items() if name.endswith(suffix)), "unit not declared")

def _aggregate_footer(fig, plotted_rows, scope):
    footer = _chart_scope(plotted_rows, "exact full-source aggregate", scope)
    fig.text(0.015, 0.012, footer, fontsize=7.5, color="#52606d", va="bottom")
    fig.tight_layout(rect=(0.01, 0.18, 0.99, 0.97))

def reader_chart_plans():
    plans = READER.get("chart_plan")
    if isinstance(plans, dict):
        plans = plans.get("charts", [])
    return [item for item in as_list(plans) if isinstance(item, dict)]

def _source_aggregate_charts():
    source_aggregates = READER.get("source_aggregates", {})
    if not isinstance(source_aggregates, dict):
        return [], []
    chart_tables = source_aggregates.get("chart_tables")
    if not chart_tables:
        return [], []
    plans = reader_chart_plans()
    plans_by_table = {
        str(first_value(
            item.get("table"), item.get("table_id"), item.get("chart_id"), item.get("id")
        )): item
        for item in plans
        if first_value(
            item.get("table"), item.get("table_id"), item.get("chart_id"), item.get("id")
        )
    }
    if isinstance(chart_tables, dict):
        entries = []
        for table_id, value in chart_tables.items():
            if isinstance(value, dict):
                entries.append({"table_id": table_id, **value})
            else:
                entries.append({"table_id": table_id, "rows": value})
    else:
        entries = [item for item in as_list(chart_tables) if isinstance(item, dict)]
    chart_priority = [str(value) for value in as_list(source_aggregates.get("chart_priority"))]
    if chart_priority:
        priority_rank = {table_id: index for index, table_id in enumerate(chart_priority)}
        entries.sort(
            key=lambda entry: (
                priority_rank.get(
                    str(first_value(entry.get("table_id"), entry.get("id"), default="")),
                    len(priority_rank),
                ),
                str(first_value(entry.get("table_id"), entry.get("id"), default="")),
            )
        )
    records, reasons = [], []
    for entry in entries[:MAX_READER_CHARTS]:
        table_id = str(first_value(entry.get("table_id"), entry.get("id"), default="chart"))
        plan = {**plans_by_table.get(table_id, {}), **entry}
        raw_rows = first_value(plan.get("rows"), plan.get("records"), plan.get("data"))
        if isinstance(raw_rows, dict):
            chart_frame = pd.DataFrame(raw_rows)
        elif isinstance(raw_rows, list):
            chart_frame = pd.DataFrame(raw_rows)
        else:
            reasons.append(f"Exact aggregate `{table_id}` has no tabular rows.")
            continue
        if chart_frame.empty:
            reasons.append(f"Exact aggregate `{table_id}` is empty.")
            continue
        kind = str(first_value(plan.get("kind"), plan.get("type"), default="line")).lower()
        columns = [str(column) for column in as_list(plan.get("columns"))]
        x = first_value(plan.get("x"), plan.get("x_column"), columns[0] if columns else None)
        y = first_value(
            plan.get("y"), plan.get("value_column"),
            columns[1] if len(columns) > 1 else None,
        )
        series = first_value(plan.get("series"), plan.get("group"), plan.get("color"))
        numeric = list(chart_frame.select_dtypes(include=[np.number]).columns)
        if y is None and numeric:
            y = numeric[-1]
        if x is None:
            candidates = [column for column in chart_frame.columns if column != y]
            x = candidates[0] if candidates else None
        if x not in chart_frame or y not in chart_frame:
            reasons.append(f"Exact aggregate `{table_id}` lacks usable x/y fields.")
            continue
        title = str(plan.get("title") or humanize(table_id))
        if re.search(r"\bvalue\b", title, flags=re.IGNORECASE):
            title = re.sub(r"\bvalue\b", humanize(str(y)), title, flags=re.IGNORECASE)
        scope = _scope_prose(plan.get("scope"))
        unit = _chart_unit(y, plan.get("unit") or OVERLAY.get("units", {}).get(y))
        plotted_rows = len(chart_frame)
        fig, ax = plt.subplots(figsize=(9, 4.8))
        if kind in {"line", "area"}:
            if chart_frame[x].nunique(dropna=True) < MIN_TREND_POINTS:
                plt.close(fig)
                reasons.append(
                    f"No exact `{table_id}` trend: fewer than {MIN_TREND_POINTS} ordered points."
                )
                continue
            if series in chart_frame:
                for label, group in chart_frame.groupby(series, dropna=False):
                    ordered = group.sort_values(x, kind="mergesort")
                    ax.plot(ordered[x], ordered[y], marker="o", markersize=2.5, label=str(label))
                if chart_frame[series].nunique(dropna=False) > 1:
                    ax.legend(frameon=False)
            else:
                ordered = chart_frame.sort_values(x, kind="mergesort")
                ax.plot(ordered[x], ordered[y], marker="o", markersize=2.5, color="#356AA0")
            if "year" in str(x).lower() and any(token in str(y).lower() for token in ("count", "row", "coverage")):
                years = pd.to_numeric(chart_frame[x], errors="coerce")
                values = pd.to_numeric(chart_frame[y], errors="coerce")
                valid = pd.DataFrame({"year": years, "value": values}).dropna().sort_values("year")
                if not valid.empty and int(valid.iloc[-1]["year"]) == pd.Timestamp.utcnow().year:
                    latest = valid.iloc[-1]
                    ax.annotate(
                        "partial year",
                        (latest["year"], latest["value"]),
                        xytext=(6, 8), textcoords="offset points", fontsize=8, color="#D1495B",
                    )
                    title += " (latest year is partial)"
                    scope += "; latest calendar year is partial"
        elif kind in {"bar", "ranking", "histogram"}:
            shown = chart_frame.head(20)
            plotted_rows = len(shown)
            labels = shown[x].astype("string")
            values = pd.to_numeric(shown[y], errors="coerce")
            if labels.str.len().max() > 12 or len(shown) > 8:
                ax.barh(labels, values, color="#356AA0")
                ax.set_xlabel(unit); ax.set_ylabel(str(x))
            else:
                ax.bar(labels, values, color="#356AA0")
                ax.set_ylabel(unit); ax.set_xlabel(str(x))
                ax.tick_params(axis="x", rotation=35)
        elif kind == "scatter":
            points = chart_frame[[x, y]].apply(pd.to_numeric, errors="coerce").dropna()
            if len(points) < MIN_SCATTER_POINTS:
                plt.close(fig)
                reasons.append(
                    f"No exact `{table_id}` scatter: only {len(points)} comparable points; "
                    f"at least {MIN_SCATTER_POINTS} are required."
                )
                continue
            ax.scatter(points[x], points[y], alpha=0.6, color="#356AA0", edgecolors="none")
            plotted_rows = len(points)
        elif kind == "heatmap":
            value = first_value(plan.get("value"), plan.get("value_column"), y)
            row = first_value(plan.get("row"), plan.get("y_axis"))
            column = first_value(plan.get("column"), plan.get("x_axis"), x)
            if row not in chart_frame or column not in chart_frame or value not in chart_frame:
                plt.close(fig)
                reasons.append(f"Exact aggregate `{table_id}` lacks heatmap row/column/value fields.")
                continue
            matrix = chart_frame.pivot_table(index=row, columns=column, values=value, aggfunc="first")
            is_anomaly = "anomaly" in table_id.lower() or "z-score" in unit.lower()
            if is_anomaly:
                finite = np.asarray(matrix.values, dtype=float)
                finite = finite[np.isfinite(finite)]
                bound = float(np.max(np.abs(finite))) if len(finite) else 1.0
                bound = bound if bound > 0 else 1.0
                image = ax.imshow(
                    matrix.values,
                    aspect="auto",
                    cmap="RdBu_r",
                    vmin=-bound,
                    vmax=bound,
                )
            else:
                image = ax.imshow(matrix.values, aspect="auto", cmap="Blues")
            x_ticks = np.unique(np.linspace(0, max(0, len(matrix.columns) - 1), min(8, len(matrix.columns))).astype(int))
            y_ticks = np.unique(np.linspace(0, max(0, len(matrix.index) - 1), min(8, len(matrix.index))).astype(int))
            ax.set_xticks(x_ticks, [matrix.columns[index] for index in x_ticks], rotation=45, ha="right")
            ax.set_yticks(y_ticks, [matrix.index[index] for index in y_ticks])
            fig.colorbar(image, ax=ax, label=unit)
        else:
            plt.close(fig)
            reasons.append(f"Exact aggregate `{table_id}` requests unsupported chart kind `{kind}`.")
            continue
        ax.set_title(title)
        if kind not in {"bar", "ranking", "histogram", "heatmap"}:
            ax.set_xlabel(str(x)); ax.set_ylabel(unit if kind != "scatter" else str(y))
        _aggregate_footer(fig, plotted_rows, scope)
        plt.show()
        records.append({
            "chart": table_id,
            "title": title,
            "plotted_rows": plotted_rows,
            "source_rows": SOURCE_ROWS,
            "analysis_rows": ANALYSIS_ROWS,
            "exactness": "exact full-source aggregate",
            "scope": scope,
            "unit": unit,
            "aggregation": "exact aggregate rows rendered without notebook recomputation",
        })
    return records, reasons

def _legacy_planned_frame_charts(frame):
    records, reasons = [], []
    for plan in reader_chart_plans():
        if len(records) >= MAX_READER_CHARTS:
            break
        status = str(plan.get("status") or "ready").lower()
        if status not in {"ready", "supported", "pass", "available"}:
            reasons.append(str(plan.get("reason") or f"Planned chart `{plan.get('chart_id')}` is {status}."))
            continue
        columns = [str(column) for column in as_list(plan.get("columns"))]
        columns = [column for column in columns if column in frame.columns]
        if not columns:
            reasons.append(f"Planned chart `{plan.get('chart_id')}` has no available columns.")
            continue
        raw_kind = str(first_value(
            plan.get("chart_type"), plan.get("type"), plan.get("kind"), default=""
        )).lower()
        if any(token in raw_kind for token in ("line", "trend", "curve", "revision", "time_series")):
            kind = "line"
        elif any(token in raw_kind for token in ("bar", "rank")):
            kind = "bar"
        elif "heat" in raw_kind:
            kind = "heatmap"
        elif any(token in raw_kind for token in ("hist", "distribution")):
            kind = "histogram"
        elif any(token in raw_kind for token in ("scatter", "relationship")):
            kind = "scatter"
        elif "box" in raw_kind:
            kind = "boxplot"
        else:
            reasons.append(
                f"Planned chart `{plan.get('chart_id')}` uses unsupported type `{raw_kind}`."
            )
            continue
        numeric = [column for column in columns if pd.api.types.is_numeric_dtype(frame[column])]
        non_numeric = [column for column in columns if column not in numeric]
        minimum_rows = int(plan.get("minimum_rows") or 1)
        title = str(plan.get("title") or humanize(plan.get("chart_id") or raw_kind))
        scope = bounded(plan.get("scope") or "frozen analysis frame", 300)
        fig, ax = plt.subplots(figsize=(9, 4.2), constrained_layout=True)
        plotted_rows = 0
        if kind == "line":
            time_column, time_order = _time_sort(frame[columns])
            y_columns = [column for column in numeric if column != time_column][:3]
            required = max(MIN_TREND_POINTS, minimum_rows)
            if time_column is None or not y_columns or time_order.nunique(dropna=True) < required:
                plt.close(fig)
                reasons.append(
                    f"No `{title}` line: fewer than {required} ordered periods or no numeric measure."
                )
                continue
            work = frame[[time_column] + y_columns].copy()
            work["__order"] = time_order
            for column in y_columns:
                work[column] = pd.to_numeric(work[column], errors="coerce")
            work = work.dropna(subset=["__order"])
            plotted = work.groupby("__order", as_index=False)[y_columns].median(numeric_only=True)
            for column in y_columns:
                ax.plot(plotted["__order"], plotted[column], marker="o", markersize=2.5, label=column)
            if len(y_columns) > 1:
                ax.legend(frameon=False, ncol=min(3, len(y_columns)))
            ax.set_xlabel(time_column)
            ax.set_ylabel("Source-native units; see column dictionary")
            plotted_rows = len(plotted)
        elif kind == "bar":
            category = non_numeric[0] if non_numeric else columns[0]
            measure = next((column for column in numeric if column != category), None)
            if measure:
                plotted = frame.groupby(category, dropna=False)[measure].median().sort_values().tail(15)
                label = OVERLAY.get("units", {}).get(measure, measure)
            else:
                plotted = frame[category].astype("string").fillna("<missing>").value_counts().head(15).sort_values()
                label = "Rows"
            if len(plotted) < max(2, minimum_rows):
                plt.close(fig)
                reasons.append(f"No `{title}` bar: too few comparable categories.")
                continue
            plotted.plot.barh(ax=ax, color="#356AA0", legend=False)
            ax.set_xlabel(label); ax.set_ylabel(category)
            plotted_rows = len(plotted)
        elif kind == "histogram":
            measure = numeric[0] if numeric else None
            values = (
                pd.to_numeric(frame[measure], errors="coerce").dropna()
                if measure else pd.Series(dtype=float)
            )
            required = max(MIN_TREND_POINTS, minimum_rows)
            if len(values) < required or values.nunique() < 4:
                plt.close(fig)
                reasons.append(f"No `{title}` distribution: insufficient populated variation.")
                continue
            bins = min(40, max(5, int(np.sqrt(len(values)))))
            ax.hist(values, bins=bins, color="#356AA0", edgecolor="white")
            ax.set_xlabel(OVERLAY.get("units", {}).get(measure, measure)); ax.set_ylabel("Rows")
            plotted_rows = len(values)
        elif kind == "scatter":
            if len(numeric) < 2:
                plt.close(fig)
                reasons.append(f"No `{title}` scatter: two numeric columns are required.")
                continue
            x, y = numeric[:2]
            points = frame[[x, y]].apply(pd.to_numeric, errors="coerce").dropna()
            required = max(MIN_SCATTER_POINTS, minimum_rows)
            if len(points) < required:
                plt.close(fig)
                reasons.append(
                    f"No `{title}` scatter: only {len(points)} comparable rows; {required} required."
                )
                continue
            ax.scatter(points[x], points[y], alpha=0.55, color="#356AA0", edgecolors="none")
            ax.set_xlabel(x); ax.set_ylabel(y)
            plotted_rows = len(points)
        elif kind == "heatmap":
            if len(columns) < 3 or not numeric:
                plt.close(fig)
                reasons.append(f"No `{title}` heatmap: row, column, and numeric value are required.")
                continue
            value = numeric[-1]
            axes = [column for column in columns if column != value][:2]
            matrix = frame.pivot_table(
                index=axes[0], columns=axes[1], values=value, aggfunc="mean"
            )
            if matrix.empty:
                plt.close(fig)
                reasons.append(f"No `{title}` heatmap: pivot is empty.")
                continue
            image = ax.imshow(matrix.values, aspect="auto", cmap="Blues")
            ax.set_xticks(range(len(matrix.columns)), matrix.columns, rotation=45, ha="right")
            ax.set_yticks(range(len(matrix.index)), matrix.index)
            fig.colorbar(image, ax=ax, label=OVERLAY.get("units", {}).get(value, value))
            plotted_rows = int(matrix.notna().sum().sum())
        else:
            measure = numeric[0] if numeric else None
            values = pd.to_numeric(frame[measure], errors="coerce").dropna() if measure else pd.Series(dtype=float)
            if len(values) < max(4, minimum_rows):
                plt.close(fig)
                reasons.append(f"No `{title}` boxplot: insufficient populated rows.")
                continue
            ax.boxplot(values, orientation="vertical", showfliers=True)
            ax.set_ylabel(OVERLAY.get("units", {}).get(measure, measure))
            plotted_rows = len(values)
        ax.set_title(title)
        fig.text(
            0.01, 0.01,
            _chart_scope(plotted_rows, EXACTNESS, scope),
            fontsize=8, color="#52606d",
        )
        plt.show()
        records.append({
            "chart": str(plan.get("chart_id") or plan.get("id") or title),
            "plotted_rows": plotted_rows,
            "exactness": EXACTNESS,
        })
    return records, reasons

def _planned_frame_charts(frame):
    payloads = _compute_reader_chart_payloads(
        frame,
        reader_chart_plans(),
        {
            **PROVENANCE,
            "source_rows": SOURCE_ROWS,
            "analysis_rows": ANALYSIS_ROWS,
            "exactness": EXACTNESS,
        },
        units=OVERLAY.get("units", {}),
        relationship_evidence=PROVENANCE.get("relationship_checks", []),
        quarantine=OUTPUT_QUARANTINE,
        max_charts=MAX_READER_CHARTS,
    )
    records, reasons, manifest = [], [], []
    for payload in payloads:
        if payload.get("status") != "ready":
            reason = payload.get("omission_reason") or "no honest payload is available."
            reasons.append(f"Planned chart `{payload.get('chart_id')}` omitted: {reason}")
            manifest.append({
                "chart_id": payload.get("chart_id"),
                "status": "omitted",
                "reason": reason,
                "source_rows": int(payload.get("source_rows") or SOURCE_ROWS or 0),
                "analysis_rows": int(payload.get("analysis_rows") or ANALYSIS_ROWS or 0),
                "plotted_rows": 0,
                "scope": payload.get("scope") or "frozen analysis frame",
                "exactness": payload.get("exactness") or EXACTNESS,
                "title": payload.get("title"),
                "unit": None,
                "aggregation": None,
            })
            continue
        figure = _render_reader_chart_payload(payload)
        if figure is None:
            reason = "renderer returned no figure."
            reasons.append(f"Planned chart `{payload.get('chart_id')}` omitted: {reason}")
            manifest.append({
                "chart_id": payload.get("chart_id"),
                "status": "omitted",
                "reason": reason,
                "source_rows": int(payload.get("source_rows") or SOURCE_ROWS or 0),
                "analysis_rows": int(payload.get("analysis_rows") or ANALYSIS_ROWS or 0),
                "plotted_rows": 0,
                "scope": payload.get("scope") or "frozen analysis frame",
                "exactness": payload.get("exactness") or EXACTNESS,
                "title": payload.get("title"),
                "unit": None,
                "aggregation": None,
            })
            continue
        display(figure)
        plt.close(figure)
        records.append(_reader_chart_scope_record(payload))
        manifest.append({
            "chart_id": payload.get("chart_id"),
            "status": "ready",
            "reason": None,
            "source_rows": int(payload.get("source_rows") or SOURCE_ROWS or 0),
            "analysis_rows": int(payload.get("analysis_rows") or ANALYSIS_ROWS or 0),
            "plotted_rows": int(payload.get("plotted_rows") or 0),
            "scope": payload.get("scope") or "frozen analysis frame",
            "exactness": payload.get("exactness") or EXACTNESS,
            "title": payload.get("title"),
            "unit": payload.get("unit"),
            "aggregation": payload.get("aggregation"),
        })
    return records, reasons, manifest

def _runtime_chart_manifest(records, reasons, *, prefix):
    manifest = [{
        "chart_id": record.get("chart") or f"{prefix}_{index + 1}",
        "status": "ready",
        "reason": None,
        "source_rows": int(record.get("source_rows") or SOURCE_ROWS or 0),
        "analysis_rows": int(record.get("analysis_rows") or ANALYSIS_ROWS or 0),
        "plotted_rows": int(record.get("plotted_rows") or 0),
        "scope": record.get("scope") or "reader runtime chart",
        "exactness": record.get("exactness") or EXACTNESS,
        "title": record.get("title") or record.get("chart"),
        "unit": record.get("unit"),
        "aggregation": record.get("aggregation"),
    } for index, record in enumerate(records)]
    for index, reason in enumerate(reasons):
        match = re.search(r"`([^`]+)`", str(reason))
        manifest.append({
            "chart_id": match.group(1) if match else f"{prefix}_omitted_{index + 1}",
            "status": "omitted",
            "reason": str(reason),
            "source_rows": int(SOURCE_ROWS or 0),
            "analysis_rows": int(ANALYSIS_ROWS or 0),
            "plotted_rows": 0,
            "scope": "runtime omission from approved reader evidence",
            "exactness": EXACTNESS,
            "title": None,
            "unit": None,
            "aggregation": None,
        })
    return manifest

def adaptive_charts():
    if OUTPUT_QUARANTINE:
        reason = "Model predictions are an output plane; value charts and relationships are quarantined."
        return [], [reason], [{
            "chart_id": "output_quarantine",
            "status": "omitted",
            "reason": reason,
            "source_rows": int(SOURCE_ROWS or 0),
            "analysis_rows": int(ANALYSIS_ROWS or 0),
            "plotted_rows": 0,
            "scope": "generated-output leakage quarantine",
            "exactness": EXACTNESS,
            "title": "Generated-output leakage quarantine",
            "unit": None,
            "aggregation": None,
        }]
    records, reasons = _source_aggregate_charts()
    if records:
        return records, reasons, _runtime_chart_manifest(records, reasons, prefix="source_aggregate")
    if FRAME is None or FRAME.empty:
        reasons.append("No frozen analysis frame is attached, so an honest chart cannot be drawn.")
        return records, reasons, _runtime_chart_manifest(records, reasons, prefix="frame")
    frame = FRAME
    planned = reader_chart_plans()
    records, planned_reasons, manifest = _planned_frame_charts(frame)
    reasons.extend(planned_reasons)
    if records:
        return records, reasons, manifest
    if planned:
        return records, reasons, manifest
    measures = _measure_columns(frame)
    time_column, time_order = _time_sort(frame)

    if (
        time_column is not None and measures
        and time_order.notna().sum() >= MIN_TREND_POINTS
        and time_order.nunique() >= MIN_TREND_POINTS
    ):
        selected = [column for column in measures if column != time_column][:3]
        plot_columns = list(dict.fromkeys([time_column, *selected]))
        plot_frame = frame[plot_columns].copy()
        plot_frame["__order"] = time_order
        plot_frame = plot_frame.dropna(subset=["__order"])
        for column in selected:
            plot_frame[column] = pd.to_numeric(plot_frame[column], errors="coerce")
        plotted = plot_frame.groupby("__order", as_index=False)[selected].median(numeric_only=True)
        plotted = plotted.dropna(how="all", subset=selected)
        if len(plotted) >= MIN_TREND_POINTS:
            chart_exactness = EXACTNESS
            if len(plotted) > CHART_MAX_POINTS:
                positions = np.linspace(0, len(plotted) - 1, CHART_MAX_POINTS, dtype=int)
                plotted = plotted.iloc[positions]
                chart_exactness = "sampled"
            fig, ax = plt.subplots(figsize=(10, 4.2), constrained_layout=True)
            for column in selected:
                ax.plot(
                    plotted["__order"], plotted[column], marker="o", markersize=2.5,
                    label=column,
                )
            ax.set_title(f"Selected measures over {time_column}")
            ax.set_xlabel(time_column)
            ax.set_ylabel("Source-native units; see column dictionary")
            if len(selected) > 1:
                ax.legend(frameon=False, ncol=min(3, len(selected)))
            fig.text(
                0.01, 0.01,
                _chart_scope(len(plotted), chart_exactness, "full time range"),
                fontsize=8, color="#52606d",
            )
            plt.show()
            records.append({
                "chart": "temporal measures", "plotted_rows": len(plotted),
                "exactness": chart_exactness,
            })
    elif time_column is not None:
        reasons.append(
            f"No line chart: `{time_column}` has fewer than {MIN_TREND_POINTS} comparable periods or no numeric measure."
        )

    if measures and len(records) < MAX_READER_CHARTS:
        column = measures[0]
        values = pd.to_numeric(frame[column], errors="coerce")
        values = values.replace([np.inf, -np.inf], np.nan).dropna()
        if len(values) >= MIN_TREND_POINTS and values.nunique() >= 4:
            plotted = values
            chart_exactness = EXACTNESS
            if len(plotted) > CHART_MAX_POINTS:
                positions = np.linspace(0, len(plotted) - 1, CHART_MAX_POINTS, dtype=int)
                plotted = plotted.iloc[positions]
                chart_exactness = "sampled"
            fig, ax = plt.subplots(figsize=(8.5, 3.8), constrained_layout=True)
            bins = min(40, max(5, int(np.sqrt(len(plotted)))))
            ax.hist(plotted, bins=bins, color="#356AA0", edgecolor="white")
            ax.set_title(f"Distribution of {column}")
            ax.set_xlabel(OVERLAY.get("units", {}).get(column, "source-native unit"))
            ax.set_ylabel("Rows")
            fig.text(
                0.01, 0.01,
                _chart_scope(len(plotted), chart_exactness, "all entities and periods"),
                fontsize=8, color="#52606d",
            )
            plt.show()
            records.append({
                "chart": f"distribution: {column}", "plotted_rows": len(plotted),
                "exactness": chart_exactness,
            })
        else:
            reasons.append(
                f"No distribution chart for `{column}`: fewer than {MIN_TREND_POINTS} populated observations or four distinct values."
            )

    categories = [
        str(column) for column in frame.columns
        if not pd.api.types.is_numeric_dtype(frame[column])
        and 2 <= frame[column].nunique(dropna=True) <= 20
        and str(column) != time_column
    ]
    if categories and len(records) < MAX_READER_CHARTS:
        column = categories[0]
        counts = frame[column].astype("string").fillna("<missing>")
        counts = counts.value_counts().head(12).sort_values()
        if len(counts) >= 2:
            fig, ax = plt.subplots(
                figsize=(8.5, max(3.2, len(counts) * 0.35)), constrained_layout=True,
            )
            counts.plot.barh(ax=ax, color="#356AA0", legend=False)
            ax.set_title(f"Most common {column} values")
            ax.set_xlabel("Rows"); ax.set_ylabel(column)
            fig.text(
                0.01, 0.01,
                _chart_scope(int(counts.sum()), EXACTNESS, "top 12 categories"),
                fontsize=8, color="#52606d",
            )
            plt.show()
            records.append({
                "chart": f"category coverage: {column}",
                "plotted_rows": int(counts.sum()), "exactness": EXACTNESS,
            })

    missing = frame.isna().mean().sort_values(ascending=False)
    missing = missing[missing.gt(0)].head(15).sort_values()
    if len(missing) and len(records) < MAX_READER_CHARTS:
        fig, ax = plt.subplots(
            figsize=(8.5, max(3.0, len(missing) * 0.32)), constrained_layout=True,
        )
        missing.plot.barh(ax=ax, color="#D99A2B", legend=False)
        ax.set_title("Columns with observed missing values")
        ax.set_xlabel("Share of analyzed rows"); ax.set_xlim(0, 1)
        fig.text(
            0.01, 0.01,
            _chart_scope(len(frame), EXACTNESS, "all rows; top 15 columns"),
            fontsize=8, color="#52606d",
        )
        plt.show()
        records.append({
            "chart": "missingness", "plotted_rows": len(frame), "exactness": EXACTNESS,
        })

    planned = reader_chart_plans()
    for plan in planned:
        if len(records) >= MAX_READER_CHARTS:
            break
        kind = str(first_value(plan.get("kind"), plan.get("type"), default="")).lower()
        if kind != "scatter":
            continue
        columns = [str(column) for column in as_list(plan.get("columns"))]
        x = first_value(plan.get("x"), columns[0] if columns else None)
        y = first_value(plan.get("y"), columns[1] if len(columns) > 1 else None)
        if x not in frame or y not in frame:
            reasons.append(f"No planned scatter: `{x}` or `{y}` is absent.")
            continue
        points = frame[[x, y]].apply(pd.to_numeric, errors="coerce").dropna()
        if len(points) < MIN_SCATTER_POINTS:
            reasons.append(
                f"No `{x}` versus `{y}` scatter: only {len(points)} comparable observations; "
                f"at least {MIN_SCATTER_POINTS} are required."
            )
            continue
        plotted = points
        chart_exactness = EXACTNESS
        if len(plotted) > CHART_MAX_POINTS:
            positions = np.linspace(0, len(plotted) - 1, CHART_MAX_POINTS, dtype=int)
            plotted = plotted.iloc[positions]
            chart_exactness = "sampled"
        fig, ax = plt.subplots(figsize=(6.5, 4.5), constrained_layout=True)
        ax.scatter(plotted[x], plotted[y], alpha=0.55, color="#356AA0", edgecolors="none")
        ax.set_title(str(plan.get("title") or f"{y} versus {x}"))
        ax.set_xlabel(str(x)); ax.set_ylabel(str(y))
        fig.text(
            0.01, 0.01,
            _chart_scope(
                len(plotted), chart_exactness,
                str(plan.get("scope") or "comparable rows"),
            ),
            fontsize=8, color="#52606d",
        )
        plt.show()
        records.append({
            "chart": f"relationship: {x} vs {y}",
            "plotted_rows": len(plotted), "exactness": chart_exactness,
        })

    if not records and not reasons:
        reasons.append(
            "Fields are too sparse or low-cardinality for an honest chart; use the table instead."
        )
    return records, reasons, _runtime_chart_manifest(records, reasons, prefix="adaptive")

## 1. TL;DR and readiness dashboard

Start here: shape, readiness, PIT safety, blockers, and the strongest computed observations.

In [2]:

show_kpi_cards(dashboard_kpis())
insights = computed_insights()
display(Markdown("### Key insights\n\n" + "\n".join(f"- {item}" for item in insights)))
blockers = PROFILE.get("blockers", [])
severe_findings = [
    finding for finding in PROFILE.get("findings", [])
    if isinstance(finding, dict)
    and str(finding.get("severity") or "").lower() in {"high", "critical"}
]
blocking_lines = list(dict.fromkeys([
    *text_items(blockers),
    *[
        f"{finding.get('title')}: {finding.get('message') or finding.get('risk')}"
        for finding in severe_findings
    ],
]))
disposition = PROFILE.get("disposition", "not assessed")
if blocking_lines:
    display(Markdown(
        f"### Blocking issues\n\n**Feature-readiness disposition:** `{disposition}`.\n\n"
        + "\n".join(f"- {item}" for item in blocking_lines)
    ))
else:
    display(Markdown(
        f"**Campaign-abort blockers:** none emitted by the source-only checks. "
        f"**Feature-readiness disposition:** `{disposition}`."
    ))

### Key insights

- 25 of 26 declared columns are present.
- Coverage spans 2010-05-01 through 2026-09-13 across 72 distinct time points.
- The evidence-only candidate grain uses 5 columns with 100.0% observed uniqueness.

### Blocking issues

**Feature-readiness disposition:** `excluded_leakage`.

- generated model-output plane is excluded from feature extraction
- Generated output plane: This table contains model outputs and is dossier-only.

## 2. The data: row meaning, shape, and columns

The complete DataFrame is shown for small sources; larger sources receive a deterministic, explicitly labelled preview.

In [3]:

display(Markdown(
    f"**Exact shape and scope.** Source rows: `{SOURCE_ROWS:,}`; analyzed shape: "
    f"`{ANALYSIS_ROWS:,} x {ANALYSIS_COLUMNS:,}`; analysis label: `{EXACTNESS}`.\n\n"
    f"**What one row means.** {row_meaning()}"
))
preview, preview_policy = safe_preview(FRAME)
display(Markdown(f"**Display policy.** {preview_policy}"))
if preview is not None:
    is_complete_small_frame = (
        not OUTPUT_QUARANTINE
        and ANALYSIS_ROWS <= FULL_DISPLAY_MAX_ROWS
        and len(preview) == ANALYSIS_ROWS
    )
    if is_complete_small_frame:
        with pd.option_context(
            "display.max_rows", max(FULL_DISPLAY_MAX_ROWS, len(preview)),
            "display.max_columns", None,
        ):
            display(preview)
    else:
        display(preview)
else:
    display(pd.DataFrame([{"status": "not available", "reason": preview_policy}]))

display(Markdown("### DataFrame info"))
if READER.get("df_info_text"):
    display(Markdown("```text\n" + str(READER["df_info_text"]) + "\n```"))
elif FRAME is not None:
    info_buffer = io.StringIO()
    FRAME.info(buf=info_buffer, verbose=True, show_counts=True)
    display(Markdown("```text\n" + info_buffer.getvalue() + "\n```"))
else:
    display(Markdown("`df.info()` is unavailable because no frozen analysis frame is attached."))

display(Markdown("### Every-column dictionary"))
display(column_dictionary())

**Exact shape and scope.** Source rows: `2,149`; analyzed shape: `2,149 x 25`; analysis label: `exact`.

**What one row means.** One row is a persisted model-output record; it is inspected only for output-plane quality and lineage, never as a feature source.

**Display policy.** schema_only_quarantine Output-plane value columns are masked.

Empty DataFrame
Columns: []
Index: []

### DataFrame info

```text
<class 'pandas.DataFrame'>
RangeIndex: 2149 entries, 0 to 2148
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   country                          2149 non-null   str
 1   crop_year                        2149 non-null   int64
 2   snapshot_stage                   544 non-null    str
 3   y_actual                         2149 non-null   float64
 4   y_pred                           2149 non-null   float64
 5   zero_anomaly_baseline            1864 non-null   float64
 6   prior_year_anomaly_baseline      1864 non-null   float64
 7   trailing_mean_anomaly_baseline   1864 non-null   float64
 8   trailing_trend_anomaly_baseline  1864 non-null   float64
 9   commodity                        2149 non-null   str
 10  tier                             2149 non-null   str
 11  feature_set_id                   1999 non-null   str
 12  target                           2149 non-null   str
 13  dataset_key                      1864 non-null   str
 14  target_key                       1864 non-null   str
 15  model_dataset_version            1864 non-null   str
 16  source_dataset_version           1864 non-null   str
 17  model                            2149 non-null   str
 18  cv_policy                        1463 non-null   str
 19  feature_set_sha                  2149 non-null   str
 20  run_id                           2149 non-null   str
 21  as_of_date                       2149 non-null   str
 22  prediction_as_of_date            544 non-null    str
 23  model_family                     2149 non-null   str
 24  prediction_date                  2149 non-null   str
dtypes: float64(6), int64(1), str(18)
memory usage: 1.1 MB

```

### Every-column dictionary

,column,dtype,unit,example,null_rate,distinct,plain_English_meaning,why_it_matters
0,country,str,not declared,not available,0%,None,Country represented by the observation.,Supports entity segmentation.
1,crop_year,int64,not declared,not available,0%,None,Crop year locating the observation on its source reporting calendar.,Provides explanatory context or a candidate diagnostic at the declared row grain.
2,snapshot_stage,str,not declared,not available,74.69%,None,Processing classification locating the row within the snapshot stage hierarchy.,Provides explanatory context or a candidate diagnostic at the declared row grain.
3,snapshot_policy,string,not declared,not available,not assessed,None,Named snapshot policy applied when producing the row.,Provides explanatory context or a candidate diagnostic at the declared row grain.
4,y_actual,float64,source-native / verify,not available,0%,None,Persisted outcome used for output evaluation; prohibited as a feature.,Provides explanatory context or a candidate diagnostic at the declared row grain.
5,y_pred,float64,source-native / verify,not available,0%,None,Persisted model prediction; prohibited as a feature.,Provides explanatory context or a candidate diagnostic at the declared row grain.
6,zero_anomaly_baseline,float64,source-native / verify,not available,13.26%,None,Reference baseline for zero anomaly used to calculate anomalies.,Provides explanatory context or a candidate diagnostic at the declared row grain.
7,prior_year_anomaly_baseline,float64,source-native / verify,not available,13.26%,None,Prior year anomaly baseline locating the observation on its source reporting calendar.,Provides explanatory context or a candidate diagnostic at the declared row grain.
8,trailing_mean_anomaly_baseline,float64,source-native / verify,not available,13.26%,None,Reference baseline for trailing mean anomaly used to calculate anomalies.,Provides explanatory context or a candidate diagnostic at the declared row grain.
9,trailing_trend_anomaly_baseline,float64,source-native / verify,not available,13.26%,None,Reference baseline for trailing trend anomaly used to calculate anomalies.,Provides explanatory context or a candidate diagnostic at the declared row grain.
10,commodity,str,not declared,not available,0%,None,Governed or source-normalized commodity identifier.,Supports entity segmentation.
11,tier,str,not declared,not available,0%,None,Processing classification locating the row within the tier hierarchy.,Provides explanatory context or a candidate diagnostic at the declared row grain.
12,feature_set_id,str,not declared,not available,6.98%,None,Stable feature set identifier used for lineage and controlled joins.,Provides explanatory context or a candidate diagnostic at the declared row grain.
13,target,str,not declared,not available,0%,None,Generated-output target identifier retained only for storage and lineage QA; it is prohibited as feature evidence.,Provides explanatory context or a candidate diagnostic at the declared row grain.
14,dataset_key,str,not declared,not available,13.26%,None,Stable dataset identifier used for lineage and controlled joins.,Provides explanatory context or a candidate diagnostic at the declared row grain.
15,target_key,str,not declared,not available,13.26%,None,Stable target identifier used for lineage and controlled joins.,Provides explanatory context or a candidate diagnostic at the declared row grain.
16,model_dataset_version,str,not declared,not available,13.26%,None,Version identifier for the model dataset artifact or logic.,Provides explanatory context or a candidate diagnostic at the declared row grain.
17,source_dataset_version,str,not declared,not available,13.26%,None,Source provenance value identifying the dataset version used to produce this row.,Provides explanatory context or a candidate diagnostic at the declared row grain.
18,model,str,not declared,not available,0%,None,Generated-output model identifier retained only for storage and lineage QA; it is prohibited as feature evidence.,Provides explanatory context or a candidate diagnostic at the declared row grain.
19,cv_policy,str,not declared,not available,31.92%,None,Named cv policy applied when producing the row.,Provides explanatory context or a candidate diagnostic at the declared row grain.
20,feature_set_sha,str,not declared,not available,0%,None,Stable content fingerprint used to identify and reproduce the originating artifact.,Provides explanatory context or a candidate diagnostic at the declared row grain.
21,run_id,str,not declared,not available,0%,None,Stable run identifier used for lineage and controlled joins.,Provides explanatory context or a candidate diagnostic at the declared row grain.
22,as_of_date,str,not declared,not available,0%,None,Snapshot date represented by the stored vintage.,Anchors temporal coverage.
23,prediction_as_of_date,str,not declared,not available,74.69%,None,Prediction as of date locating the observation on its source reporting calendar.,Provides explanatory context or a candidate diagnostic at the declared row grain.
24,model_family,str,not declared,not available,0%,None,Physical model family partition value used to establish source coverage.,Controls physical coverage.
25,prediction_date,str,not declared,not available,0%,None,Date associated with the generated prediction record.,Controls physical coverage.

## 3. Quality scorecard

A short PASS/CAVEAT/BLOCKER view replaces the old metric dump. Unsupported checks say `NOT ASSESSED`; a zero-row denominator never becomes 0%.

In [4]:

quality = quality_scorecard()
display(quality)
raw_consumer_checks = [
    item for item in PROVENANCE.get("source_specific_checks", [])
    if item.get("view") == "raw_vs_documented_consumer_dedup"
]
if raw_consumer_checks:
    display(Markdown("### Raw source versus documented consumer view"))
    display(pd.DataFrame([
        {"evidence": bounded(item, 4000), "exactness": item.get("exactness", EXACTNESS)}
        for item in raw_consumer_checks
    ]))

,check,status,evidence
0,Schema contract,CAVEAT,Observed schema differs from the registry declaration.
1,Grain and uniqueness,BLOCKER,The registry does not declare a natural key.
2,Missingness,CAVEAT,The highest column null rate is 74.7%.
3,Contextual value validity,NOT ASSESSED,"Output-plane numeric value validity is quarantined; schema, null, freshness, partition, and duplicate QA remain in s..."
4,Temporal cadence,CAVEAT,Largest gap (231 days) materially exceeds the median cadence (45 days).
5,Temporal coverage,PASS,Coverage runs from 2010-05-01 through 2026-09-13.
6,Schema drift by file or era,CAVEAT,Footer-derived schema stability needs review: 8 distinct schema fingerprints were observed.
7,Arithmetic identities,NOT_ASSESSED,No governed arithmetic identity is declared.
8,Feature-plane boundary,BLOCKER,Generated model output is excluded from feature evidence to prevent leakage.

## 4. Entity and vocabulary coverage

Cardinality and mapping evidence show which entities and categories are actually represented.

In [5]:

configured_coverage = READER.get("coverage")
source_entity_coverage = (
    (READER.get("source_aggregates") or {}).get("entity_coverage")
    if isinstance(READER.get("source_aggregates"), dict) else None
)
coverage_rows = []
if isinstance(source_entity_coverage, dict) and source_entity_coverage:
    coverage_rows.extend([
        {
            "column": column,
            "distinct": values.get("distinct_count"),
            "top_values": bounded(values.get("top_values"), 1600),
            "exactness": "exact over source_rows",
            "source_rows": SOURCE_ROWS,
        }
        for column, values in source_entity_coverage.items()
    ])

# Numeric codes are often valid entity axes but are intentionally absent from
# categorical vocabulary profiling.  Include only axes explicitly configured
# for entity display, and compute them from the attached frozen frame.
configured_entity_columns = []
configured_entity_columns.extend(as_list(READER.get("preview_strata")))
for kpi in as_list(READER.get("dashboard_kpis")):
    if isinstance(kpi, dict) and str(kpi.get("kind") or "") == "distinct_entities":
        configured_entity_columns.extend(as_list(kpi.get("columns")))
chart_plan = READER.get("chart_plan") or {}
for chart in as_list(chart_plan.get("charts") if isinstance(chart_plan, dict) else chart_plan):
    if isinstance(chart, dict):
        configured_entity_columns.extend(as_list(chart.get("series_dimensions")))
existing_columns = {str(row.get("column")) for row in coverage_rows}
if FRAME is not None:
    for column in dict.fromkeys(map(str, configured_entity_columns)):
        if column in existing_columns or column not in FRAME:
            continue
        series = FRAME[column]
        lower = column.lower()
        entity_like = (
            lower.endswith(("_code", "_id"))
            or any(token in lower for token in (
                "commodity", "country", "entity", "geography", "market",
                "port", "region", "state", "station", "territory",
            ))
        )
        if not entity_like:
            continue
        counts = series.dropna().value_counts().head(10)
        coverage_rows.append({
            "column": column,
            "distinct": int(series.nunique(dropna=True)),
            "top_values": bounded(
                [{"value": str(value), "rows": int(count)} for value, count in counts.items()],
                1600,
            ),
            "exactness": (
                "exact over source_rows"
                if EXACTNESS == "exact" and ANALYSIS_ROWS == SOURCE_ROWS
                else f"{EXACTNESS} over analyzed_rows"
            ),
            "source_rows": SOURCE_ROWS,
        })

vocabularies = metric_value("entity_vocabulary_coverage", "vocabularies", {}) or {}
for column, values in sorted(vocabularies.items()):
    if str(column) in {str(row.get("column")) for row in coverage_rows}:
        continue
    coverage_rows.append(
        {
            "column": column,
            "distinct": values.get("distinct_count"),
            "top_values": bounded(values.get("top_values"), 1600),
            "rare_categories": values.get("rare_category_count"),
            "rare_row_rate": values.get("rare_row_rate"),
            "normalization_collisions": len(values.get("normalisation_collisions", {})),
            "exactness": EXACTNESS,
        }
    )
if coverage_rows:
    display(pd.DataFrame(coverage_rows).sort_values("distinct", ascending=False).head(30))
elif isinstance(configured_coverage, list) and configured_coverage:
    display(pd.DataFrame(configured_coverage))
elif isinstance(configured_coverage, dict) and configured_coverage:
    display(pd.DataFrame([{"measure": key, "value": bounded(value, 1000)} for key, value in configured_coverage.items()]))
else:
    display(
        pd.DataFrame([{"status": "not assessed", "reason": "No vocabulary profile is available."}])
    )
interpretation(
    "Vocabulary checks support governed mappings; matching strings alone do not authorize a join."
)

,column,distinct,top_values,exactness,source_rows,rare_categories,rare_row_rate,normalization_collisions
2,as_of_date,72,"[{""count"": 1205, ""rate"": 0.560725919032108, ""value"": ""2026-06-27""}, {""count"": 150, ""rate"": 0.06979990693345742, ""val...",exact,NaN,68.0,0.253141,0.0
10,run_id,15,"[{""count"": 272, ""rate"": 0.1265704979060028, ""value"": ""0e45564b0db4467ba80ec98aacf79dbd""}, {""count"": 272, ""rate"": 0.1...",exact,NaN,0.0,0.000000,0.0
13,tier,4,"[{""count"": 1455, ""rate"": 0.677059097254537, ""value"": ""preseason_physical""}, {""count"": 272, ""rate"": 0.126570497906002...",exact,NaN,0.0,0.000000,0.0
11,snapshot_stage,4,"[{""count"": 136, ""rate"": 0.25, ""value"": ""early_inseason""}, {""count"": 136, ""rate"": 0.25, ""value"": ""late_inseason""}, {""...",exact,NaN,0.0,0.000000,0.0
6,feature_set_sha,4,"[{""count"": 1455, ""rate"": 0.677059097254537, ""value"": ""931e6651d7ac71ad3e0a837db15f7ec3694c67bd6b072edb4ec678d795c399...",exact,NaN,0.0,0.000000,0.0
1,country,4,"[{""rows"": 541, ""value"": ""argentina""}, {""rows"": 541, ""value"": ""brazil""}, {""rows"": 541, ""value"": ""united_states""}, {""r...",exact over source_rows,2149.0,NaN,NaN,NaN
8,model_dataset_version,3,"[{""count"": 1205, ""rate"": 0.6464592274678111, ""value"": ""20260627T121215Z_phase5_psd_smoke""}, {""count"": 544, ""rate"": 0...",exact,NaN,0.0,0.000000,0.0
5,feature_set_id,3,"[{""count"": 1455, ""rate"": 0.727863931965983, ""value"": ""preseason_physical""}, {""count"": 272, ""rate"": 0.136068034017008...",exact,NaN,0.0,0.000000,0.0
3,cv_policy,3,"[{""count"": 748, ""rate"": 0.5112781954887218, ""value"": ""expanding_post_2000""}, {""count"": 429, ""rate"": 0.29323308270676...",exact,NaN,0.0,0.000000,0.0
4,dataset_key,3,"[{""count"": 1205, ""rate"": 0.6464592274678111, ""value"": ""psd_snd_anomaly""}, {""count"": 544, ""rate"": 0.2918454935622318,...",exact,NaN,0.0,0.000000,0.0
9,model_family,3,"[{""count"": 919, ""rate"": 0.42764076314564914, ""value"": ""psd_production_anomaly""}, {""count"": 686, ""rate"": 0.3192182410...",exact,NaN,0.0,0.000000,0.0
7,model,2,"[{""count"": 1184, ""rate"": 0.550953932061424, ""value"": ""lightgbm""}, {""count"": 965, ""rate"": 0.4490460679385761, ""value""...",exact,NaN,0.0,0.000000,0.0
0,commodity,1,"[{""rows"": 2149, ""value"": ""corn_cbot""}]",exact over source_rows,2149.0,NaN,NaN,NaN
12,source_dataset_version,1,"[{""count"": 1864, ""rate"": 1.0, ""value"": ""20260626T010217Z_6725de02_phase7_full""}]",exact,NaN,0.0,0.000000,0.0

**Interpretation.** Vocabulary checks support governed mappings; matching strings alone do not authorize a join.

## 5. Missingness and validity

Nulls, sentinels, infinities, zeros, and negatives are separated so structural gaps are not mistaken for signal.

In [6]:

configured_missingness = READER.get("missingness")
source_column_statistics = (
    (READER.get("source_aggregates") or {}).get("column_statistics")
    if isinstance(READER.get("source_aggregates"), dict) else None
)
if isinstance(source_column_statistics, dict) and source_column_statistics:
    missing_frame = pd.DataFrame([
        {
            "column": column,
            "null_count": values.get("null_count"),
            "null_rate": values.get("null_rate"),
            "denominator": SOURCE_ROWS,
            "exactness": "exact over source_rows",
        }
        for column, values in source_column_statistics.items()
    ]).sort_values(["null_rate", "column"], ascending=[False, True])
elif isinstance(configured_missingness, list) and configured_missingness:
    missing_frame = pd.DataFrame(configured_missingness)
elif FRAME is not None and ANALYSIS_ROWS > 0:
    missing_frame = pd.DataFrame({
        "column": FRAME.columns,
        "null_count": [int(FRAME[column].isna().sum()) for column in FRAME.columns],
        "null_rate": [float(FRAME[column].isna().mean()) for column in FRAME.columns],
        "denominator": ANALYSIS_ROWS,
        "exactness": EXACTNESS,
    }).sort_values(["null_rate", "column"], ascending=[False, True])
else:
    missing_frame = pd.DataFrame([
        {"status": "not assessed", "reason": "No positive row denominator; rates are not shown as zero."}
    ])
missing_display = missing_frame.copy()
if "null_rate" in missing_display:
    missing_display["null_rate"] = missing_display["null_rate"].map(rate_display)
display(missing_display)
validity = None if OUTPUT_QUARANTINE else metric_value(
    "missingness_validity", "validity_summary", None
)
if OUTPUT_QUARANTINE:
    display(Markdown(
        "**Validity evidence:** numeric output-value validity is quarantined. "
        "The null/coverage QA above remains in scope and does not inspect output magnitudes."
    ))
elif validity:
    display(Markdown("**Validity evidence.** " + bounded(validity, 5000)))

,column,null_count,null_rate,denominator,exactness
22,prediction_as_of_date,1605,74.69%,2149,exact
2,snapshot_stage,1605,74.69%,2149,exact
18,cv_policy,686,31.92%,2149,exact
13,dataset_key,285,13.26%,2149,exact
15,model_dataset_version,285,13.26%,2149,exact
6,prior_year_anomaly_baseline,285,13.26%,2149,exact
16,source_dataset_version,285,13.26%,2149,exact
14,target_key,285,13.26%,2149,exact
7,trailing_mean_anomaly_baseline,285,13.26%,2149,exact
8,trailing_trend_anomaly_baseline,285,13.26%,2149,exact
5,zero_anomaly_baseline,285,13.26%,2149,exact
11,feature_set_id,150,6.98%,2149,exact
21,as_of_date,0,0%,2149,exact
9,commodity,0,0%,2149,exact
0,country,0,0%,2149,exact
1,crop_year,0,0%,2149,exact
19,feature_set_sha,0,0%,2149,exact
17,model,0,0%,2149,exact
23,model_family,0,0%,2149,exact
24,prediction_date,0,0%,2149,exact
20,run_id,0,0%,2149,exact
12,target,0,0%,2149,exact
10,tier,0,0%,2149,exact
3,y_actual,0,0%,2149,exact
4,y_pred,0,0%,2149,exact

**Validity evidence:** numeric output-value validity is quarantined. The null/coverage QA above remains in scope and does not inspect output magnitudes.

## 6. Ordinary descriptive statistics

Familiar `describe()` statistics come before specialist tail metrics. Output-plane value columns remain quarantined.

In [7]:

describe_frame = ordinary_describe()
display(describe_frame)
display(Markdown(
    f"*Statistics cover {ANALYSIS_ROWS:,} analyzed rows ({EXACTNESS}). "
    "Outliers are described and retained; this notebook does not delete or impute them.*"
))

,status,reason
0,withheld_output_quarantine,Reader statistics contain no displayable records.

*Statistics cover 2,149 analyzed rows (exact). Outliers are described and retained; this notebook does not delete or impute them.*

## 7. What the data says

Charts are selected from the available grain and sample size. Sparse trends and underpowered relationships are replaced with an explicit rationale.

In [8]:

chart_records, chart_omissions, chart_manifest = adaptive_charts()
if chart_records:
    display(Markdown("### Chart scope register"))
    display(pd.DataFrame(chart_records))
else:
    rationale = " ".join(chart_omissions) or "No evidence-led chart is supported."
    display(Markdown("**No chart shown:** " + rationale))
if chart_omissions and chart_records:
    display(Markdown("**Charts intentionally omitted:**\n\n" + "\n".join(f"- {item}" for item in chart_omissions)))

display(Markdown("### Chart execution manifest"))
display(pd.DataFrame(chart_manifest))
display({
    "application/vnd.leviathan.chart-manifest+json": chart_manifest,
    "text/plain": json.dumps(chart_manifest, sort_keys=True),
}, raw=True)

display(Markdown("### Notable observations"))
display(notable_observations())
display(Markdown("### Evidence-backed insights\n\n" + "\n".join(f"- {item}" for item in insights)))

**No chart shown:** Model predictions are an output plane; value charts and relationships are quarantined.

### Chart execution manifest

,chart_id,status,reason,source_rows,analysis_rows,plotted_rows,scope,exactness,title,unit,aggregation
0,output_quarantine,omitted,Model predictions are an output plane; value charts and relationships are quarantined.,2149,2149,0,generated-output leakage quarantine,exact,Generated-output leakage quarantine,None,None

[{"aggregation": null, "analysis_rows": 2149, "chart_id": "output_quarantine", "exactness": "exact", "plotted_rows": 0, "reason": "Model predictions are an output plane; value charts and relationships are quarantined.", "scope": "generated-output leakage quarantine", "source_rows": 2149, "status": "omitted", "title": "Generated-output leakage quarantine", "unit": null}]

### Notable observations

Empty DataFrame
Columns: []
Index: []

### Evidence-backed insights

- 25 of 26 declared columns are present.
- Coverage spans 2010-05-01 through 2026-09-13 across 72 distinct time points.
- The evidence-only candidate grain uses 5 columns with 100.0% observed uniqueness.

## 8. Within-source relationships

Relationships are descriptive and source-internal. No target appears, and sparse pairs are not promoted into correlation claims.

In [9]:

if OUTPUT_QUARANTINE:
    display(pd.DataFrame([{
        "status": "quarantined",
        "reason": "Prediction/output values are prohibited from relationship analysis.",
    }]))
else:
    pairs = metric_value("within_source_relationships", "correlation_pairs", []) or []
    pair_frame = pd.DataFrame(pairs)
    if not pair_frame.empty:
        n_column = next(
            (column for column in ("effective_n", "n", "sample_size") if column in pair_frame),
            None,
        )
        if n_column:
            pair_frame = pair_frame.loc[
                pd.to_numeric(pair_frame[n_column], errors="coerce").ge(MIN_SCATTER_POINTS)
            ]
    display(
        pair_frame.head(30) if not pair_frame.empty else
        pd.DataFrame([{
            "status": "not assessed",
            "reason": f"No eligible pair has at least {MIN_SCATTER_POINTS} comparable observations.",
        }])
    )
interpretation("Association can flag redundancy; it does not establish causation or target value.")

,status,reason
0,quarantined,Prediction/output values are prohibited from relationship analysis.

**Interpretation.** Association can flag redundancy; it does not establish causation or target value.

## 9. PIT and leakage: what was knowable when?

Observation time, release time, knowledge time, and final/latest values are kept distinct.

In [10]:

configured_pit = first_value(
    READER.get("pit_summary"), READER.get("pit"), READER.get("pit_notes")
)
if isinstance(configured_pit, list) and configured_pit:
    display(pd.DataFrame(configured_pit))
elif isinstance(configured_pit, dict) and configured_pit:
    display(pd.DataFrame([{"question": key, "answer": bounded(value, 1400)} for key, value in configured_pit.items()]))
else:
    display(pd.DataFrame([
        {"question": "Knowledge column", "answer": CONTRACT.get("knowledge_date_col") or "not governed"},
        {"question": "Knowledge semantics", "answer": CONTRACT.get("knowledge_semantics") or "not governed"},
        {"question": "Publication lag", "answer": CONTRACT.get("publication_lag_days") if CONTRACT.get("publication_lag_days") is not None else "not governed"},
        {"question": "Vintage retention", "answer": CONTRACT.get("vintage_retention") or "not declared"},
        {"question": "Source-level feature gate", "answer": "eligible" if metric_value("pit_leakage", "feature_eligible_source", False) else "blocked / diagnostic only"},
    ]))
hazards = text_items(OVERLAY.get("known_hazards"))
if hazards:
    display(Markdown("### Leakage and semantic hazards\n\n" + "\n".join(f"- {item}" for item in hazards)))
if OUTPUT_QUARANTINE and FRAME is not None and not FRAME.empty:
    reference_dates = []
    for item in as_list(PROVENANCE.get("object_sample")):
        if isinstance(item, dict) and item.get("last_modified"):
            parsed = pd.to_datetime(item["last_modified"], errors="coerce", utc=True)
            if not pd.isna(parsed):
                reference_dates.append(parsed)
    campaign_match = re.search(r"((?:19|20)\d{6})", str(PROVENANCE.get("campaign_id") or ""))
    if campaign_match:
        parsed = pd.to_datetime(campaign_match.group(1), format="%Y%m%d", errors="coerce", utc=True)
        if not pd.isna(parsed):
            reference_dates.append(parsed)
    governed_dates = []
    for column in ("as_of_date", "prediction_as_of_date", "prediction_date"):
        if column not in FRAME or column in VALUE_COLUMNS:
            continue
        parsed = pd.to_datetime(FRAME[column], errors="coerce", utc=True)
        if parsed.notna().any():
            governed_dates.append((column, parsed.max()))
    if reference_dates and governed_dates:
        reference = max(reference_dates)
        future_dates = [(column, value) for column, value in governed_dates if value > reference]
        if future_dates:
            column, value = max(future_dates, key=lambda item: item[1])
            display(Markdown(
                "**Output coverage warning.** "
                f"`{column}` reaches `{value.date()}`, after the latest reproducible source-object/"
                f"campaign capture reference `{reference.date()}`. This may be an intentional "
                "forecast horizon, but it must not be read as historical availability. "
                "No prediction or outcome values were inspected."
            ))
interpretation(
    "A useful source is not automatically PIT-safe. Prototype features only after their cutoff-time availability is explicit."
)

,question,answer
0,analysis_rows,2149
1,exactness,exact
2,explanation,Generated model outputs are never eligible feature sources.
3,knowledge_date_column,None
4,knowledge_semantics,None
5,notes,"[""No governed knowledge-time column is declared; descriptive source EDA is valid, but feature prototypes need an exp..."
6,plotted_rows,None
7,publication_lag_days,None
8,source_rows,2149
9,status,excluded_leakage
10,use_rule,"Do not derive, correlate, join to targets, or propose features from this table."

### Leakage and semantic hazards

- Generated model outputs are prohibited feature inputs and remain excluded_leakage.
- Candidate grain may be inferred for quality evidence only, never promoted as contract.
- Model-output plane: prohibited as a feature source and classified excluded_leakage.
- Placeholder/broken catalog partitions have existed historically; profile them as quality evidence only.
- Registry lacks a complete natural-key/value-column contract; inferred grain is evidence only and cannot be promoted automatically.

**Output coverage warning.** `as_of_date` reaches `2026-09-13`, after the latest reproducible source-object/campaign capture reference `2026-07-18`. This may be an intentional forecast horizon, but it must not be read as historical availability. No prediction or outcome values were inspected.

**Interpretation.** A useful source is not automatically PIT-safe. Prototype features only after their cutoff-time availability is explicit.

## 10. Join readiness

Only governed commodity, geography, and time relationships are considered; name coincidence is not a join rule.

In [11]:

relations = PROVENANCE.get("relationship_checks", [])
join_columns = metric_value("join_readiness", "candidate_join_columns", []) or []
display(pd.DataFrame([{
    "candidate_join_columns": bounded(join_columns),
    "governed_checks_run": len(relations),
    "registry_coverage_axis": bounded(metric_value("join_readiness", "registry_coverage_axis", None)),
    "promotion_rule": "Any row expansion or unresolved mapping blocks promotion.",
    "exactness": EXACTNESS,
}]))
if relations:
    display(pd.DataFrame(relations).head(30))
else:
    display(Markdown("**No pairwise join was inferred.** A governed relationship must be declared first."))

,candidate_join_columns,governed_checks_run,registry_coverage_axis,promotion_rule,exactness
0,"[""as_of_date"", ""commodity"", ""country"", ""crop_year""]",0,None,Any row expansion or unresolved mapping blocks promotion.,exact

**No pairwise join was inferred.** A governed relationship must be declared first.

## 11. Feature opportunities and anti-features

Proposals are review records, not enabled features. Timing and lag rules are shown next to each idea.

In [12]:

candidates = SUMMARY.get("feature_candidates", [])
if OUTPUT_QUARANTINE:
    assert not candidates and PROFILE.get("disposition") == "excluded_leakage"
candidate_frame = pd.DataFrame(candidates)
candidate_columns = [
    "candidate_id", "classification", "mechanism", "source_columns",
    "aggregation_window", "lag", "unit", "knowledge_time_rule", "readiness",
]
if not candidate_frame.empty:
    # Prefer breadth across source measures.  Candidate generation commonly
    # emits several transforms per measure; a reader preview of the first six
    # would otherwise hide every later feature-bearing column.
    representative_indexes = []
    seen_surfaces = set()
    for index, candidate in candidate_frame.iterrows():
        source_columns = as_list(candidate.get("source_columns"))
        transformation = candidate.get("transformation")
        primary = (
            transformation.get("column")
            if isinstance(transformation, dict) and transformation.get("column")
            else (source_columns[0] if source_columns else candidate.get("candidate_id"))
        )
        surface = str(primary)
        if surface in seen_surfaces:
            continue
        seen_surfaces.add(surface)
        representative_indexes.append(index)
        if len(representative_indexes) == 6:
            break
    visible_candidates = candidate_frame.loc[representative_indexes, [
        column for column in candidate_columns if column in candidate_frame
    ]]
    display(visible_candidates)
    if len(candidate_frame) > len(visible_candidates):
        display(Markdown(
            f"*Showing {len(visible_candidates)} representative ideas out of "
            f"{len(candidate_frame)} review-only candidates. The complete catalog is in "
            "`feature_candidates.yaml`.*"
        ))
else:
    rationale = first_value(
        READER.get("no_candidate_rationale"), OVERLAY.get("no_candidate_reason"),
        (SUMMARY.get("feature_opportunity_map", {}).get("no_candidate_rationale", {}) or {}).get("value"),
        default="No evidence-backed candidate survived source-quality gates.",
    )
    display(pd.DataFrame([{"candidate_status": "none", "reason": rationale}]))

anti_features = text_items(READER.get("anti_features"))
anti_summary = READER.get("anti_feature_summary")
if isinstance(anti_summary, dict):
    for entry in anti_summary.get("entries", []):
        if isinstance(entry, dict) and entry.get("statement"):
            text = str(entry["statement"])
            if entry.get("reason"):
                text += " - " + str(entry["reason"])
            anti_features.append(text)
else:
    anti_features += text_items(anti_summary)
anti_features += text_items(
    (SUMMARY.get("feature_opportunity_map", {}).get("do_not_derive", {}) or {}).get("value")
)
if OUTPUT_QUARANTINE:
    anti_features.append("Do not derive features from model predictions or output-plane values.")
display(Markdown(
    "### Do not derive\n\n" + (
        "\n".join(f"- {item}" for item in dict.fromkeys(anti_features))
        if anti_features else "- No table-specific anti-feature was supplied; PIT and semantic gates still apply."
    )
))
display(Markdown(
    "**Promotion boundary:** a separate human review is required; this EDA never edits production feature configuration."
))

  candidate_status                                        reason
0             none  Model outputs are prohibited feature inputs.

### Do not derive

- Do not derive any feature from this generated-output table. - Targets, predictions, actuals, residuals, and model metadata can leak outcomes.
- Model predictions, actual outcomes, baselines, run identifiers, and output metadata are prohibited input features. - Reviewed table-specific exclusion.
- Do not compute target associations, performance charts, or feature candidates from this table. - Reviewed table-specific exclusion.
- Do not infer a production key from observed output rows and silently promote it. - Reviewed table-specific exclusion.
- Do not derive features from model predictions or output-plane values.

**Promotion boundary:** a separate human review is required; this EDA never edits production feature configuration.

## 12. Bottom line and work orders

The final reader decision states what is useful now and exactly what must be repaired before prototyping.

In [13]:

findings = PROFILE.get("findings", [])
work_orders = []
for finding in findings:
    work_orders.append({
        "priority": finding.get("severity"),
        "finding": finding.get("title"),
        "why_it_matters": finding.get("risk") or finding.get("message"),
        "required_action": finding.get("remediation") or "Document and review the semantic decision.",
        "evidence": finding.get("evidence"),
    })
if not CONTRACT.get("knowledge_date_col") and CONTRACT.get("publication_lag_days") is None:
    work_orders.append({
        "priority": "high",
        "finding": "PIT availability is not governed",
        "why_it_matters": "Current/final source values may not have been known at prediction cutoff.",
        "required_action": "Contract publication or availability lag before feature prototyping.",
        "evidence": "pit_leakage",
    })
display(
    pd.DataFrame(work_orders).head(50) if work_orders else
    pd.DataFrame([{
        "priority": "none",
        "required_action": "Review evidence-backed candidates; make no automatic production change.",
    }])
)
scope = SUMMARY["analysis_scope"]
assert scope["source_layer"] == "silver"
assert scope["legacy_gold_read"] is False and scope["model_ready_read"] is False
assert scope["target_aware_analysis"] is False
assert scope["production_feature_config_mutated"] is False
display(Markdown(
    f"**Disposition:** `{PROFILE.get('disposition', 'not assessed')}`. "
    "Source-only boundary checks passed; feature promotion remains separate."
))

,priority,finding,why_it_matters,required_action,evidence
0,critical,Generated output plane,Using it as a feature source would introduce direct outcome/model leakage.,Keep candidate output empty and enforce the source boundary in readers.,[pit_leakage.feature_eligible_source]
1,high,PIT availability is not governed,Current/final source values may not have been known at prediction cutoff.,Contract publication or availability lag before feature prototyping.,pit_leakage

**Disposition:** `excluded_leakage`. Source-only boundary checks passed; feature promotion remains separate.

## Appendix A. Compact provenance and reproducibility

Hashes and object identities stay available without interrupting the analytical story.

In [14]:

preferred_fields = [
    "campaign_id", "git_sha", "registry_fingerprint", "spec_hash",
    "frozen_frame_sha256", "object_count", "source_total_rows", "source_total_bytes",
    "sampling_policy", "seed", "image_digest",
]
provenance_rows = [
    {
        "field": field,
        "value": bounded(first_value(
            PROVENANCE.get(field),
            READER.get("provenance", {}).get(field)
            if isinstance(READER.get("provenance"), dict) else None,
        ), 1600),
        "exactness": "exact",
    }
    for field in preferred_fields
    if field in PROVENANCE or (
        isinstance(READER.get("provenance"), dict)
        and field in READER["provenance"]
    )
]
provenance_rows.extend([
    {"field": "frame_uri", "value": FRAME_URI or "embedded / not attached", "exactness": "exact"},
    {"field": "manifest_uri", "value": MANIFEST_URI or "not attached", "exactness": "exact"},
    {"field": "analysis_exactness", "value": EXACTNESS, "exactness": "exact"},
    {"field": "source_rows", "value": SOURCE_ROWS, "exactness": "footer-derived" if EXACTNESS == "sampled" else EXACTNESS},
    {"field": "analysis_rows", "value": ANALYSIS_ROWS, "exactness": EXACTNESS},
])
display(pd.DataFrame(provenance_rows).drop_duplicates(subset=["field"]))
display(Markdown(
    "The complete machine profile remains embedded in the notebook payload and adjacent `summary.json`; "
    "the immutable object inventory remains in the campaign manifest."
))

,field,value,exactness
0,campaign_id,readerfirst-final-20260718-a176abf1,exact
1,git_sha,e6146c826dbcd927127104b4bfcb9bb526ddf6b1,exact
2,frozen_frame_sha256,7bcd0ab29e160c1b053f7698ea9afed45c5e0c351c59219ddc3c384756b4f5fe,exact
3,object_count,15,exact
4,source_total_rows,2149,exact
5,source_total_bytes,256457,exact
6,image_digest,sha256:e9563290bdc62d3216841dfb190b59ef709ac5c5d2e4fc0b894c72de5548bed1,exact
7,frame_uri,s3://leviathan-dev-shahem-001/eda/silver/campaign_id=readerfirst-final-20260718-a176abf1/table=silver_model_predicti...,exact
8,manifest_uri,s3://leviathan-dev-shahem-001/eda/silver/campaign_id=readerfirst-final-20260718-a176abf1/table=silver_model_predicti...,exact
9,analysis_exactness,exact,exact
10,source_rows,2149,exact
11,analysis_rows,2149,exact

The complete machine profile remains embedded in the notebook payload and adjacent `summary.json`; the immutable object inventory remains in the campaign manifest.